/* song.js - Strict Version (Original Titles Kept, Artist Added) */
window.allSongsLibrary = [
    // --- Mon (月曜日) ---
    { title: "真夜中のドアstay with me", artist: "松原みき", src: "https://cdn-assets.bestelysia.com/月曜日/真夜中のドアstay_with_me.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/真夜中のドアStay With Me.lrc",  category: "mon" },
    { title: "Someday ft Emarie シンシアのロンドン物語", artist: "Cynthia / Emarie", src: "https://cdn-assets.bestelysia.com/月曜日/Someday_ft._Emarie_シンシアのロンドン物語.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/Someday.lrc", category: "mon" },
    
    // --- Tue (火曜日) ---
    { title: "不該", artist: "周杰倫 & 張惠妹", src: "https://cdn-assets.bestelysia.com/火曜日/JayChou_aMEI_不該.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/不该withaMEI.lrc", category: "tue" },
    { title: "黑色毛衣", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/火曜日/JayChou_黑色毛衣.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/JayChou_黑色毛衣.lrc", category: "tue" },
    { title: "爱的华尔兹", artist: "若雾唐媛", src: "https://cdn-assets.bestelysia.com/火曜日/爱的华尔兹_若雾唐媛.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/爱的华尔兹严艺丹.lrc", category: "tue" },
    { title: "感謝你曾來過", artist: "Ayo97 ft.阿涵", src: "https://cdn-assets.bestelysia.com/火曜日/Ayo97_感謝你曾來過_ft.阿涵.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/感谢你曾来过Ayo97周思涵.lrc", category: "tue" },
    { title: "夜曲", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/火曜日/JayChou_夜曲.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/夜曲周杰伦.lrc", category: "tue" },
    { title: "擱淺", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/火曜日/周杰倫_擱淺.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/搁浅Live周杰伦.lrc", category: "tue" },
    { title: "春嬌與志明", artist: "街道辦 & 歐陽耀瑩", src: "https://cdn-assets.bestelysia.com/火曜日/春嬌與志明街道辦歐陽耀瑩.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/春娇与志明街道办GDC欧阳耀莹.lrc", category: "tue" },
    { title: "訣愛", artist: "詹雯婷", src: "https://cdn-assets.bestelysia.com/火曜日/訣愛_詹雯婷.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/诀爱ay詹雯婷.lrc", category: "tue" },
    { title: "漂洋过海来看你", artist: "刘明湘", src: "https://cdn-assets.bestelysia.com/火曜日/015.刘明湘 - 漂洋过海来看你.wav", cover: "assets/Elysia11.jpg", lrc: "lyrics/漂洋过海来看你刘明湘.lrc", category: "tue" },
    { title: "手心的蔷薇", artist: "林俊傑 & 鄧紫棋", src: "https://cdn-assets.bestelysia.com/火曜日/06 手心的蔷薇(feat.邓紫棋).wav", cover: "assets/Elysia11.jpg", lrc: "lyrics/手心的蔷薇林俊杰邓紫棋.lrc", category: "tue" },
    { title: "被风吹过的夏天", artist: "林俊傑 & 金莎", src: "https://cdn-assets.bestelysia.com/火曜日/10. 被风吹过的夏天.wav", cover: "assets/Elysia11.jpg", lrc: "lyrics/被风吹过的夏天金莎林俊杰.lrc", category: "tue" },
    { title: "你在看孤独的风景", artist: "单小源 & 本兮", src: "https://cdn-assets.bestelysia.com/火曜日/单小源、本兮 - 你在看孤独的风景【有间音乐】.wav", cover: "assets/nizaikangududefengjing .webp", lrc: "lyrics/你在看孤独的风景本兮单小源.lrc", category: "tue" },
    { title: "風鈴", artist: "蔣孜怡", src: "https://cdn-assets.bestelysia.com/火曜日/蔣孜怡-風鈴(FallingU中文版).mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/风铃蒋孜怡.lrc", lrc: "lyrics/Someday.lrc", category: "tue" },
    { title: "星晴", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/火曜日/周杰伦 - 星晴 + 回到过去 + 最后的战役 + 爱我别走 (Live).mp3", cover: "assets/xingqing.webp", lrc: "lyrics/星晴回到过去最后的战役爱我别走.lrc", category: "tue" },
    { title: "暗号", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/火曜日/周杰伦 - 暗号.flac", cover: "assets/anhao.webp", lrc: "lyrics/暗号周杰伦.lrc", category: "tue" },
    { title: "无限速", artist: "本兮 & 阿悄", src: "https://cdn-assets.bestelysia.com/火曜日/本兮&阿悄 - 无限速.flac", cover: "assets/wuxiansu.webp", lrc: "lyrics/无限速本兮阿悄.lrc", category: "tue" },
    { title: "心墙", artist: "林俊杰", src: "https://cdn-assets.bestelysia.com/火曜日/心墙.wav", cover: "assets/xinqiang.webp", lrc: "lyrics/心墙林俊杰.lrc", category: "tue" },
    { title: "听海", artist: "张惠妹", src: "https://cdn-assets.bestelysia.com/火曜日/张惠妹 - 听海.wav", cover: "assets/tinghai.webp", lrc: "lyrics/听海张惠妹.lrc", category: "tue" },
    { title: "处处吻", artist: "杨千嬅", src: "https://cdn-assets.bestelysia.com/火曜日/杨千嬅 - 处处吻.mp3", cover: "assets/ccw.webp", lrc: "lyrics/处处吻杨千嬅.lrc", category: "tue" },
    { title: "你不是真正的快乐", artist: "邓紫棋", src: "https://cdn-assets.bestelysia.com/火曜日/邓紫棋 - 你不是真正的快乐.wav", cover: "assets/nbszzdkl.webp", lrc: "lyrics/你不是真正的快乐Live邓紫棋.lrc", category: "tue" },
    { title: "一直很安静", artist: "阿桑", src: "https://cdn-assets.bestelysia.com/火曜日/阿桑 - 一直很安静.wav", cover: "assets/Elysia11.jpg", lrc: "lyrics/一直很安静阿桑.lrc", category: "tue" },
    { title: "珊瑚海", artist: "周杰倫 & 梁心颐", src: "https://cdn-assets.bestelysia.com/火曜日/周杰伦、梁心颐 - 珊瑚海.flac", cover: "assets/Elysia11.jpg", lrc: "lyrics/珊瑚海周杰伦Lara梁心颐.lrc", category: "tue" },
    { title: "怎么了", artist: "周杰倫 & 袁咏琳", src: "https://cdn-assets.bestelysia.com/火曜日/周杰伦;袁咏琳 - 怎么了.flac", cover: "assets/Elysia11.jpg", lrc: "lyrics/怎么了周杰伦袁咏琳.lrc", category: "tue" },
    { title: "花海", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/火曜日/周杰伦 - 花海.flac", cover: "assets/Elysia11.jpg", lrc: "lyrics/花海周杰伦.lrc", category: "tue" },
    { title: "爱在西元前", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/火曜日/周杰伦 - 爱在西元前 (Live).flac", cover: "assets/Elysia11.jpg", lrc: "lyrics/爱在西元前live.lrc", category: "tue" },
    
    { title: "清廉なるHeretics", artist: "毛蟹 feat.坂本真綾", src: "https://cdn-assets.bestelysia.com/月曜日/清廉なるHeretics.mp3", cover: "assets/ql.webp", lrc: "lyrics/清廉.lrc", category: "mon" },
    { title: "帝国少女", artist: "R Sound Design", src: "https://cdn-assets.bestelysia.com/月曜日/帝国少女.mp3", cover: "assets/dgsn.webp", lrc: "lyrics/帝国少女初音未来.lrc", category: "mon" },
    { title: "深海少女", artist: "Yuuyu-P", src: "https://cdn-assets.bestelysia.com/月曜日/深海少女.mp3", cover: "assets/shsn.webp", lrc: "lyrics/深海少女.lrc", category: "mon" },
    { title: "KISS OF DEATH", artist: "中島美嘉", src: "https://cdn-assets.bestelysia.com/月曜日/KISS OF DEATH.mp3", cover: "assets/kissofdeath.webp", lrc: "lyrics/KISS中岛美嘉.lrc", category: "mon" },
    { title: "月と花束さユり", artist: "酸欠少女さユり", src: "https://cdn-assets.bestelysia.com/月曜日/月と花束さユりSayuri.mp3", cover: "assets/yzsh.webp", lrc: "lyrics/月と花束月与花束.lrc", category: "mon" },
    { title: "自傷無色", artist: "Nekobolo", src: "https://cdn-assets.bestelysia.com/月曜日/自傷無色.mp3", cover: "assets/zsws.webp", lrc: "lyrics/自傷無色.lrc", category: "mon" },
    { title: "銀の龍の背に乗って", artist: "中島美雪", src: "https://cdn-assets.bestelysia.com/月曜日/中島美雪_ 銀の龍の背に乗って.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/銀の龍の背に乗って中岛美雪.lrc", category: "mon" },
    { title: "こころなし", artist: "Majiko", src: "https://cdn-assets.bestelysia.com/月曜日/いよ 酷いよもういっそ僕の體を.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/清廉.lrc", category: "mon" },
    { title: "再見只是陌生人", artist: "莊心妍", src: "https://cdn-assets.bestelysia.com/火曜日/再見只是陌生人.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/清廉.lrc", category: "tue" },
    { title: "如愿", artist: "王菲", src: "https://cdn-assets.bestelysia.com/火曜日/如愿.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/清廉.lrc", category: "tue" },
    { title: "爱我还是他", artist: "陶喆", src: "https://cdn-assets.bestelysia.com/火曜日/爱我还是他.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/清廉.lrc", category: "tue" },
    { title: "心生七面 善惡難辨", artist: "KBShinya", src: "https://cdn-assets.bestelysia.com/火曜日/心生七面善惡難辨.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/心生七面善恶难辨.lrc", category: "tue" },
    { title: "梦回还", artist: "呦貓UNEKO", src: "https://cdn-assets.bestelysia.com/火曜日/梦回还.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/清廉.lrc", category: "tue" },
    { title: "房間", artist: "刘瑞琦", src: "https://cdn-assets.bestelysia.com/火曜日/房間新版.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/清廉.lrc", category: "tue" },
    
    { title: "淪陷", artist: "王靖雯不胖", src: "https://cdn-assets.bestelysia.com/水曜日/淪陷.mp3", cover: "assets/lunxian.webp", lrc: "lyrics/沦陷.lrc", category: "wed" },
    { title: "羅生門 Follow", artist: "梨凍院", src: "https://cdn-assets.bestelysia.com/水曜日/羅生門Follow.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/罗生门Follow.lrc", category: "wed" },
    { title: "Reyi心跳的證明", artist: "劉人語", src: "https://cdn-assets.bestelysia.com/水曜日/Reyi心跳的證明電影.mp3", cover: "assets/xintiaodezhengming.webp", lrc: "lyrics/心跳的证明-刘人语.lrc", category: "wed" },
    { title: "裂縫中的陽光", artist: "林俊傑", src: "https://cdn-assets.bestelysia.com/水曜日/裂縫中的陽光.mp3", cover: "assets/liefengzhongdeyangguang.webp", lrc: "lyrics/裂缝中的阳光-林俊杰.lrc", category: "wed" },
    
    { title: "時空縫隙", artist: "苏星婕", src: "https://cdn-assets.bestelysia.com/日曜日/時空縫隙.mp3", cover: "assets/shikongfengxi.webp", lrc: "lyrics/时空缝隙.lrc", category: "sun" },
    { title: "日落的人海", artist: "小水", src: "https://cdn-assets.bestelysia.com/日曜日/日落的人海.mp3", cover: "assets/riluoderenhai.webp", lrc: "lyrics/日落的人海.lrc", category: "sun" },
    { title: "大概是我在说梦话", artist: "怪豆儿&KevinGee", src: "https://cdn-assets.bestelysia.com/日曜日/大概是我在说梦话.mp3", cover: "assets/dagaishiwozaishuomenghua.webp", lrc: "lyrics/大概是我在说梦话.lrc", category: "sun" },
    { title: "偏偏爱太重", artist: "徐健铭&细妹", src: "https://cdn-assets.bestelysia.com/日曜日/偏偏爱太重.mp3", cover: "assets/pianpianaitaizhong.webp", category: "sun" },
    { title: "心碎的声音", artist: "黑豆ADO", src: "https://cdn-assets.bestelysia.com/日曜日/Tiếnglòngvỡtan.mp3", cover: "assets/xinsuideshengyin.webp", category: "sun" },
    { title: "愛在深夜裡最難翻篇", artist: "en", src: "https://cdn-assets.bestelysia.com/日曜日/en愛在深夜裡最難翻篇.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "穿越时空", artist: "苏星婕", src: "assets/穿越时空.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/穿越时空星婕.lrc", category: "sun" },
    { title: "過分依賴", artist: "en", src: "https://cdn-assets.bestelysia.com/日曜日/en過分依賴.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "两相欢", artist: "音闕詩聽 & 昆玉", src: "https://cdn-assets.bestelysia.com/日曜日/两相欢音阙诗听昆玉.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "把遺憾還給你", artist: "以安", src: "https://cdn-assets.bestelysia.com/日曜日/以安把遺憾還給你.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "街角的晚风", artist: "励志豪 & 神勇尼尼", src: "https://cdn-assets.bestelysia.com/日曜日/励志豪神勇尼尼街角的晚风.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "舊情綿綿", artist: "半根蘿蔔", src: "https://cdn-assets.bestelysia.com/日曜日/半根蘿蔔舊情綿綿.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "红豆", artist: "卷笔刀阿卷", src: "https://cdn-assets.bestelysia.com/日曜日/卷笔刀阿卷红豆.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "和平分手", artist: "徐良 & 小暖", src: "https://cdn-assets.bestelysia.com/日曜日/和平分手徐良小暖.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "多远都要在一起", artist: "G.E.M.鄧紫棋", src: "https://cdn-assets.bestelysia.com/日曜日/多远都要在一起RnbbeatZxxy.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "后来遇见他", artist: "胡66", src: "https://cdn-assets.bestelysia.com/日曜日/大头针后来遇见他.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "春涧", artist: "大头针", src: "https://cdn-assets.bestelysia.com/日曜日/大头针春涧.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "情绪失控", artist: "季彦霖", src: "https://cdn-assets.bestelysia.com/日曜日/季彦霖情绪失控.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "定格", artist: "未知", src: "https://cdn-assets.bestelysia.com/日曜日/定格.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "怎麼會不遺憾呢", artist: "小兮橙", src: "https://cdn-assets.bestelysia.com/日曜日/小兮橙怎麼會不遺憾呢.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "流离", artist: "彭pini", src: "https://cdn-assets.bestelysia.com/日曜日/彭pini流离.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "就讓故事裡的人留在故事裡", artist: "拾三三", src: "https://cdn-assets.bestelysia.com/日曜日/拾三三就讓故事裡的人留在故事裡.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "故事還長", artist: "雲汐", src: "https://cdn-assets.bestelysia.com/日曜日/故事還長雲汐.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "明日坐标", artist: "林俊傑", src: "https://cdn-assets.bestelysia.com/日曜日/明日坐标王者荣耀十周年版本主题曲林俊杰王者荣耀.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "雨蝶", artist: "李翊君", src: "https://cdn-assets.bestelysia.com/日曜日/李翊君雨蝶.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "期許", artist: "燈叔", src: "https://cdn-assets.bestelysia.com/日曜日/燈叔期許.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "爱的故事上集", artist: "孙耀威", src: "https://cdn-assets.bestelysia.com/日曜日/爱的故事上集.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "他比我好吧", artist: "王理文", src: "https://cdn-assets.bestelysia.com/日曜日/王理文他比我好吧後來你遇見的他.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "他和她", artist: "耗子", src: "https://cdn-assets.bestelysia.com/日曜日/耗子他和她.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "沈园外", artist: "阿YueYue & 戾格", src: "https://cdn-assets.bestelysia.com/日曜日/阿YueYue戾格沈园外.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "等我不愛你", artist: "陳墨一 & 吖毛", src: "https://cdn-assets.bestelysia.com/日曜日/陳墨一吖毛等我不愛你我不再.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "漸冷", artist: "雪二", src: "https://cdn-assets.bestelysia.com/日曜日/雪二漸冷.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "願妳余生漫長", artist: "王貳浪", src: "https://cdn-assets.bestelysia.com/日曜日/願妳余生漫長王貳浪.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "风吹秋霜一地白", artist: "未知", src: "https://cdn-assets.bestelysia.com/日曜日/风吹秋霜一地白.mp3", cover: "assets/Elysia11.jpg", category: "sun" },

    { title: "PSYCHO-PASS 2 ED", artist: "EGOIST", src: "https://cdn-assets.bestelysia.com/月曜日/テレビアニメPSYCHO-PASS サイコパス 2エンディングテーマ.mp3", cover: "assets/Elysia11.jpg", category: "mon" },
    { title: "名前のない怪物", artist: "EGOIST", src: "https://cdn-assets.bestelysia.com/月曜日/名前のない怪物.mp3", cover: "assets/Elysia11.jpg", category: "mon" },
    { title: "See-Saw去り際のロマンティ", artist: "See-Saw", src: "https://cdn-assets.bestelysia.com/月曜日/See-Saw去り際のロマンティ.mp3", cover: "assets/Elysia11.jpg", category: "mon" },
    { title: "to the beginning", artist: "Kalafina", src: "https://cdn-assets.bestelysia.com/月曜日/tothebeginning.mp3", cover: "assets/Elysia11.jpg", category: "mon" },
    { title: "Zoetrope (AMNESIA OP)", artist: "Nagi Yanagi", src: "https://cdn-assets.bestelysia.com/月曜日/AMVアムネシアOPAMNESIA OPZoetrope.mp3", cover: "assets/Elysia11.jpg", category: "mon" }, 
    { title: "What is forever love", artist: "Lia", src: "https://cdn-assets.bestelysia.com/月曜日/Whatisforeverlove.mp3", cover: "https://cdn-assets.bestelysia.com/covers/whatisforeverlove.JPG", category: "mon" },
    { title: "The Way I Still Love You", artist: "Reyi", src: "https://cdn-assets.bestelysia.com/土曜日/ThewayIstillloveyou.mp3", cover: "assets/Elysia11.jpg", category: "sat" },
    { title: "会呼吸的痛", artist: "米塔", src: "https://cdn-assets.bestelysia.com/土曜日/MisideMitaAMVFullSong米塔の小曲会呼吸的痛-DJ.mp3", cover: "https://cdn-assets.bestelysia.com/covers/米诺.jpg", category: "sat" },
    { title: "珊瑚海 X One Last Time", artist: "Jay Chou x Ariana", src: "https://cdn-assets.bestelysia.com/土曜日/珊瑚海 X One Last Time(混响版).mp3", cover: "assets/Elysia11.jpg", category: "sat" },
    { title: "Angel", artist: "Yoon Mi Rae", src: "https://cdn-assets.bestelysia.com/水曜日/中字尹美莱Angel.mp3", cover: "assets/angel.webp", lrc: "lyrics/Angel尹美莱.lrc", category: "wed" },
    { title: "我只能離開", artist: "劉思達", src: "https://cdn-assets.bestelysia.com/水曜日/劉思達LOFTHESTAR我只能離開.mp3", cover: "assets/wozhinenglikai.webp", lrc: "lyrics/罗生门Follow.lrc", category: "wed" },
    { title: "橘子汽水", artist: "南拳媽媽", src: "https://cdn-assets.bestelysia.com/水曜日/南拳媽媽橘子汽水.mp3", cover: "assets/juziqishui.webp", lrc: "lyrics/橘子汽水-南拳妈妈.lrc", category: "wed" },
    { title: "園遊會", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/水曜日/周杰倫園遊會.mp3", cover: "assets/yuanyouhui.webp", lrc: "lyrics/园游会-周杰伦.lrc", category: "wed" },
    { title: "愛的飛行日記", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/水曜日/周杰倫愛的飛行日記.mp3", cover: "assets/aidefeixingriji.webp", lrc: "lyrics/爱的飞行日记.lrc", category: "wed" },
    { title: "遇到", artist: "方雅賢", src: "https://cdn-assets.bestelysia.com/水曜日/方雅賢遇到.mp3", cover: "assets/yudao.webp", lrc: "lyrics/遇到-方雅贤.lrc", category: "wed" },
    { title: "夏天", artist: "李玖哲", src: "https://cdn-assets.bestelysia.com/水曜日/李玖哲NickyLee夏天Summer-完整版MV.mp3", cover: "assets/xiatian.webp", lrc: "lyrics/夏天-李玖哲.lrc", category: "wed" },
    { title: "熱戀夏季", artist: "楊郡安", src: "https://cdn-assets.bestelysia.com/水曜日/楊郡安熱戀夏季.mp3", cover: "assets/relianxiaji.webp", lrc: "lyrics/热恋夏季-杨郡安.lrc", category: "wed" },
    { title: "夏天的风", artist: "温岚", src: "https://cdn-assets.bestelysia.com/水曜日/温岚夏天的风.mp3", cover: "assets/xiatiandefeng.webp", lrc: "lyrics/夏天的风-温岚.lrc", category: "wed" },
    { title: "全世界的人都知道", artist: "王俞勻", src: "https://cdn-assets.bestelysia.com/水曜日/王俞勻全世界的人都知道MV.mp3", cover: "assets/quanshijiederendouzhidao.webp", lrc: "lyrics/全世界的人都知道-王俞匀.lrc", category: "wed" },
    { title: "恶作剧", artist: "王蓝茵", src: "https://cdn-assets.bestelysia.com/水曜日/王蓝茵恶作剧.mp3", cover: "assets/ezuoju.webp", lrc: "lyrics/恶作剧-蓝心羽.lrc", category: "wed" },
    { title: "能不能", artist: "鐵竹堂 & 溫嵐", src: "https://cdn-assets.bestelysia.com/水曜日/能不能鐵竹堂&溫嵐.mp3", cover: "assets/nengbuneng.webp", lrc: "lyrics/能不能-温岚&JZN.lrc", category: "wed" },
    { title: "突然一場雨", artist: "藍心羽", src: "https://cdn-assets.bestelysia.com/水曜日/藍心羽突然一場雨.mp3", cover: "assets/turanyichangyu.webp", lrc: "lyrics/突然一场雨-蓝心羽.lrc", category: "wed" },
    { title: "直到你降臨我", artist: "阿肆", src: "https://cdn-assets.bestelysia.com/水曜日/阿肆直到你降臨我.mp3", cover: "assets/zhidaonijianglin.webp", lrc: "lyrics/直到你降临-阿肆.lrc", category: "wed" },
    { title: "其實你懂我", artist: "陳喬恩", src: "https://cdn-assets.bestelysia.com/水曜日/陳喬恩其實你懂我.mp3", cover: "assets/Elysia11.jpg", category: "wed" }, 
    { title: "光陰副本", artist: "林俊傑", src: "https://cdn-assets.bestelysia.com/水曜日/光陰副本.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/光阴副本.lrc", category: "wed" },
    { title: "在月蝕裡抱緊我", artist: "林俊傑", src: "https://cdn-assets.bestelysia.com/水曜日/林俊傑在月蝕裡抱緊我.flac", cover: "assets/Elysia11.jpg", lrc: "lyrics/在月蚀里抱紧我.lrc", category: "wed" }, 
    { title: "黑夜問白天", artist: "林俊傑", src: "https://cdn-assets.bestelysia.com/水曜日/林俊傑黑夜問白天.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/黑夜问白天-林俊杰.lrc", category: "wed" },

    { title: "曹操", artist: "林俊傑", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/02. 曹操.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "黑色幽默", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/02. 黑色幽默.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "水仙", artist: "王心凌", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/03 水仙.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "不懂", artist: "林俊傑", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/03. 不懂.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "唯一", artist: "王力宏", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/03. 唯一.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "莎士比亚的天份", artist: "林俊傑", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/04. 莎士比亚的天份.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "江南", artist: "林俊傑", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/06. 江南.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "明天", artist: "吴克群", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/06. 明天.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "乌兰巴托的夜", artist: "鸿雁组合", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/09 乌兰巴托的夜--鸿雁组合(1).wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "简简单单", artist: "林俊傑", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/07. 简简单单.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "爱不会绝迹", artist: "林俊傑", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/09. 爱不会绝迹.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "转动", artist: "林俊傑", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/10. 转动.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "江南", artist: "林俊傑", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/12. 江南.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "终于等到你", artist: "孙露", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/12.终于等到你--孙露.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "她说", artist: "林俊傑", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/15. 她说.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "爱笑的眼睛", artist: "林俊傑", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/16. 爱笑的眼睛.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "one last time remix", artist: "Ariana Grande", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/one last time(remix).wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "友人說", artist: "林俊傑", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/友人說.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "不该 with aMEI", artist: "周杰倫 & 張惠妹", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 不该 (with aMEI) (《幻城》电视剧主题曲).flac", cover: "assets/Elysia11.jpg", lrc: "lyrics/不该withaMEI.lrc",  category: "unknown" },
    { title: "以父之名", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 以父之名 (Live).flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "你听得到", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 你听得到 (Live).flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "你怎么连话都说不清楚 live", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 你怎么连话都说不清楚 (Live).flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    
    { title: "半岛铁盒", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 半岛铁盒 (Live).flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "印第安老斑鸠", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 印第安老斑鸠.flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "反方向的钟", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 反方向的钟.flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "彩虹", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 彩虹.flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "开不了口 live", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 开不了口 (Live).flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "夜曲", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 夜曲.flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "手写的从前", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 手写的从前.flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "搁浅 live", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 搁浅 (Live).flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "借口", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 借口.flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "枫", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 枫.flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "白色风车", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 白色风车.flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "给我一首歌的时间", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 给我一首歌的时间.flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "稻香", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 稻香.flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "蒲公英的约定", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 蒲公英的约定.flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "说好的幸福呢", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 说好的幸福呢＋淘汰＋青花瓷 (Live).flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "超人不会飞", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 超人不会飞.flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "退后", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 退后.flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "逆鳞", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 逆鳞.flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "爱的飞行日记", artist: "周杰倫 & 杨瑞代", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦;杨瑞代 - 爱的飞行日记.flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "等你下课", artist: "周杰倫 & 杨瑞代", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦&杨瑞代 - 等你下课.mp3", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "给我一首歌的时间 live", artist: "周杰倫 & 蔡依林", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦;蔡依林 - 给我一首歌的时间(live).mp3", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "爱笑的眼睛", artist: "徐若瑄", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/爱笑的眼睛.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "我可以抱你吗", artist: "张惠妹", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/张惠妹 - 我可以抱你吗.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "我很想爱他", artist: "Twins", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/我很想爱他.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "慢慢喜欢你", artist: "莫文蔚", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/莫文慰 - 慢慢喜欢你.flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "阴天", artist: "莫文蔚", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/莫文蔚 - 阴天【有间音乐】.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "寂寞在唱歌", artist: "阿桑", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/阿桑 - 寂寞在唱歌.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "K歌之王", artist: "陈奕迅", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/陈奕迅 - K歌之王粤语【有间音乐】.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "莫失莫忘", artist: "阿桑", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/阿桑 - 莫失莫忘.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "零度的親吻", artist: "林俊傑", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/零度的親吻.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
     
    { title: "My Soul, Your Beats!", artist: "Lia (Piano Arr.)", src: "assets/My Soul, Your Beats! -Piano Arrange Ver.-.mp3", cover: "assets/My Soul, Your Beats! -Piano Arrange Ver.-.jpg", category: "piano" },
    { title: "My Most Precious Treasure", artist: "Angel Beats!", src: "assets/My Most Precious Treasure (From My Most Precious Treasure).mp3", cover: "assets/Key anime piano medley.jpg", category: "piano" },
    { title: "Shiteki de Souseiteki na Tori-tachi e no Shirabe", artist: "Angel Beats!", src: "assets/Shiteki de Souseiteki na Tori-tachi e no Shirabe (Yokunin no Tame no Piano Sanka).mp3", cover: "assets/Shiteki.jpg", category: "piano" },
    { title: "Last regrets foretting me", artist: "Kanon (Piano)", src: "assets/Last regrets,foretting me.mp3", cover: "assets/Last regrets, foretting me.jpg", lrc: "lyrics/lastregrets.lrc", category: "piano" },
    { title: "Megumeru Gensoukyoku", artist: "CLANNAD (Piano)", src: "assets/Megumeru Gensoukyoku.mp3", cover: "assets/Megumeru Gensoukyoku.jpg", category: "piano" },
    { title: "Call of Silence", artist: "Hiroyuki Sawano", src: "assets/Call of Silence (From Attack on Titian) Piano Cover.mp3", cover: "assets/Call of Silence.jpg", category: "piano" },
    { title: "Only my Railgun OP1 fripSide", artist: "fripSide (Piano)", src: "assets/Only my Railgun - A Certain Scientific Railgun OP1 [Piano]  fripSide.mp3", cover: "assets/Level5.jpg", category: "piano" },
    { title: "Aoi Tori - The iDOLM", artist: "The iDOLM@STER", src: "assets/[Pianeet] Aoi Tori - The iDOLM@STER OST - Piano Tutorial  Synthesia.mp3", cover: "assets/Aoi Tori - The iDOLM.jpg", category: "piano" },
    { title: "鬼滅之刃 OPLiSA - 紅蓮華", artist: "LiSA (Piano)", src: "assets/Gurenge - Demon Slayer OP [Piano].mp3", cover: "assets/Shinobu Kocho.jpg", category: "piano" },
    { title: "Flower Dance - DJ Okawari", artist: "DJ Okawari", src: "assets/Flower Dance - DJ Okawari (Piano Cover by Riyandi Kusuma).mp3", cover: "assets/Flower Dance - DJ Okawari.jpg", category: "piano" },
    { title: "theme of SSS -Piano Arrange ", artist: "Angel Beats!", src: "assets/theme of SSS -Piano Arrange Ver.-.mp3", cover: "assets/theme of SSS.jpg", category: "piano" },
    { title: "My Soul Your Beats", artist: "Angel Beats!", src: "assets/My Soul, Your Beats! ~Classic~ Instrumental.mp3", cover: "assets/My Soul, Your Beats! ~Classic~ Instrumental.jpg", category: "piano" },
    { title: "Pachelbel's Canon", artist: "Bi.Bi Piano", src: "assets/Bi.Bi PianoPachelbel's Canon 终于弹了这首 世界上最治愈的钢琴曲卡农.mp3", cover: "assets/banner1.jpg", category: "piano" },
    { title: "Heroism endures in nothingness", artist: "Hoyo-Mix", src: "assets/英雄主义-在虚无中永存.mp3", cover: "assets/Elysia11.jpg", category: "piano" },
    { title: "诀别书", artist: "Piano Cover", src: "assets/钢琴演奏诀别书纯音乐精编完整版.mp3", cover: "assets/Elysia11.jpg", category: "piano" },
    { title: "Key anime piano medley", artist: "Key Sounds Label", src: "assets/Air (TV), Kanon (2006), Clannad After Story - Key anime piano medley.mp3", cover: "assets/Key anime piano medley.jpg", category: "piano" },
    { title: "Crying for Rain", artist: "Minami (Piano)", src: "assets/Crying for Rain (Kawaki wo Ameku) - Domestic na Kanojo OP [Piano]  Minami.mp3", cover: "assets/banner1.jpg", category: "piano" },
    { title: "GIRLS BAND CRY", artist: "TOGENASHI TOGEARI", src: "assets/GIRLS BAND CRY OP - Wrong World - Piano Cover  TOGENASHI TOGEARI.mp3", cover: "assets/GIRLS BAND CRY.jpg", category: "piano" },
    { title: "Hikari no Senritsu", artist: "Animenz (Kalafina)", src: "assets/Hikari no Senritsu - Sora no Woto OP Arr. Animenz (2024 Fan Remaster Visualized).mp3", cover: "assets/banner1.jpg", category: "piano" },
    { title: "LEVEL5 -judgelight", artist: "fripSide (Piano)", src: "assets/LEVEL5 -judgelight- A Certain Scientific Railgun OP2 [Piano].mp3", cover: "assets/banner1.jpg", category: "piano" },
    { title: "Flower Dance Super Trick Version", artist: "DJ Okawari", src: "assets/Flower Dance Super Trick Version (mp3cut.net).mp3", cover: "assets/Flower Dance - DJ Okawari.jpg", category: "piano" },
    { title: "Departures - Guilty Crown ED1", artist: "EGOIST (Piano)", src: "assets/Departures - Guilty Crown ED1 [Piano].mp3", cover: "assets/Elysia11.jpg", category: "piano" },
    { title: "Majo no Tabitabi", artist: "Piano Cover", src: "assets/Majo no Tabitabi OPLiterature Piano Cover.mp3", cover: "assets/Majo no Tabitabi.jpg", category: "piano" },
    { title: "My Dearest ", artist: "Supercell (Piano)", src: "assets/My Dearest - Guilty Crown OP [10 Year Anniversary Edition] [Piano].mp3", cover: "assets/Mydearest.jpg", category: "piano" },
    { title: "Ninelie Kabaneri", artist: "Aimer w/ Chelly", src: "assets/Ninelie - Kabaneri of the Iron Fortress ED [Piano].mp3", cover: "assets/ninelie.jpg", category: "piano" },
    { title: "One Last Kiss", artist: "Hikaru Utada (Piano)", src: "assets/One Last Kiss - Evangelion_ 3.0  1.0 Theme Song [Piano]  Hikaru Utada.mp3", cover: "assets/one last kiss.jpg", category: "piano" },
    { title: "secret base", artist: "Zone (Piano)", src: "assets/secret base - Kimi ga Kureta Mono - AnoHana ED [Piano].mp3", cover: "assets/secret base.jpg", category: "piano" },
    { title: "Blue Bird 2022 ver", artist: "Ikimono-gakari", src: "assets/Blue Bird (2022 ver.) - Naruto Shippuuden OP3 [Piano]  Ikimono-gakari.mp3", cover: "assets/banner1.jpg", category: "piano" },
    { title: "Hikaru Nara - Your Lie in Apri", artist: "Goose House (Piano)", src: "assets/Hikaru Nara - Your Lie in April OP1 [Piano].mp3", cover: "assets/Elysia11.jpg", category: "piano" },
    { title: "AKIBA POP the Future - Pianeet", artist: "Pianeet", src: "assets/AKIBA POP the Future - Pianeet [Piano Transcription].mp3", cover: "assets/banner1.jpg", category: "piano" },
    { title: "SWORD ART ONLINE", artist: "Animenz", src: "assets/SWORD ART ONLINE PIANO MEDLEY!!! (30,000 Subscribers Special).mp3", cover: "assets/SWORD ART ONLINE.jpg", category: "piano" },
    { title: "Merry Christmas, Mr. Lawrence 1986", artist: "Ryuichi Sakamoto", src: "assets/merry.mp3", cover: "assets/banner1.jpg", category: "piano" },
    { title: "反方向的钟", artist: "周杰倫", src: "assets/反方向的钟.mp3", cover: "assets/Elysia11.jpg", category: "piano" },
    { title: "给我一首歌的时间", artist: "周杰倫", src: "assets/给我一首歌的时间 piano ver-.mp3", cover: "assets/banner1.jpg", category: "piano" },
    { title: "晴天", artist: "Bi.Bi Piano", src: "assets/周杰伦晴天 钢琴独奏 Jay ChouBi.Bi Piano.mp3", cover: "assets/banner1.jpg", category: "piano" },
    { title: "溯", artist: "CORSAK", src: "assets/su.mp3", cover: "assets/Elysia11.jpg", category: "piano" },
    { title: "潮汐", artist: "Imagine Dragons", src: "assets/Natural.mp3", cover: "assets/Elysia11.jpg", category: "piano" },
    { title: "游京", artist: "东雪莲", src: "assets/游京 东雪莲.mp3", cover: "assets/游京 东雪莲.jpg", category: "piano" },
    { title: "还是会想你", artist: "林达浪", src: "assets/还是会想你曼波 (mp3cut.net) 2.mp3", cover: "assets/Elysia11.jpg", category: "piano" },
    { title: "Duvert 四季 Merry mixed", artist: "Mixed", src: "assets/mix.mp3", cover: "assets/Elysia11.jpg", category: "piano" }
  ];
