/* song.js - Strict Version (Original Titles Kept, Artist Added) */
window.allSongsLibrary = [
    // --- Mon (月曜日) ---
    { title: "真夜中のドアstay with me", artist: "松原みき", src: "https://cdn-assets.bestelysia.com/月曜日/真夜中のドアstay_with_me.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/真夜中のドアStay With Me.lrc",  category: "mon" },
    { title: "Someday ft Emarie シンシアのロンドン物語", artist: "Cynthia / Emarie", src: "https://cdn-assets.bestelysia.com/月曜日/Someday_ft._Emarie_シンシアのロンドン物語.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/Someday.lrc", category: "mon" },
    
    // --- Tue (火曜日) ---
    { title: "不該", artist: "周杰倫 & 張惠妹", src: "https://cdn-assets.bestelysia.com/火曜日/JayChou_aMEI_不該.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/不该withaMEI.lrc", category: "tue" },
    { title: "黑色毛衣", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/火曜日/JayChou_黑色毛衣.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/JayChou_黑色毛衣.lrc", category: "tue" },
    { title: "爱的华尔兹", artist: "若雾唐媛", src: "https://cdn-assets.bestelysia.com/火曜日/爱的华尔兹_若雾唐媛.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/爱的华尔兹严艺丹.lrc", category: "tue" },
    { title: "感謝你曾來過", artist: "Ayo97 ft.阿涵", src: "https://cdn-assets.bestelysia.com/火曜日/Ayo97_感謝你曾來過_ft.阿涵.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/感谢你曾来过Ayo97周思涵.lrc", category: "tue" },
    { title: "夜曲", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/火曜日/JayChou_夜曲.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/夜曲周杰伦.lrc", category: "tue" },
    { title: "擱淺", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/火曜日/周杰倫_擱淺.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/搁浅Live周杰伦.lrc", category: "tue" },
    { title: "春嬌與志明", artist: "街道辦 & 歐陽耀瑩", src: "https://cdn-assets.bestelysia.com/火曜日/春嬌與志明街道辦歐陽耀瑩.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/春娇与志明街道办GDC欧阳耀莹.lrc", category: "tue" },
    { title: "訣愛", artist: "詹雯婷", src: "https://cdn-assets.bestelysia.com/火曜日/訣愛_詹雯婷.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/诀爱ay詹雯婷.lrc", category: "tue" },
    { title: "漂洋过海来看你", artist: "刘明湘", src: "https://cdn-assets.bestelysia.com/火曜日/015.刘明湘 - 漂洋过海来看你.wav", cover: "assets/Elysia11.jpg", lrc: "lyrics/漂洋过海来看你刘明湘.lrc", category: "tue" },
    { title: "手心的蔷薇", artist: "林俊傑 & 鄧紫棋", src: "https://cdn-assets.bestelysia.com/火曜日/06 手心的蔷薇(feat.邓紫棋).wav", cover: "assets/Elysia11.jpg", lrc: "lyrics/手心的蔷薇林俊杰邓紫棋.lrc", category: "tue" },
    { title: "被风吹过的夏天", artist: "林俊傑 & 金莎", src: "https://cdn-assets.bestelysia.com/火曜日/10. 被风吹过的夏天.wav", cover: "assets/Elysia11.jpg", lrc: "lyrics/被风吹过的夏天金莎林俊杰.lrc", category: "tue" },
    { title: "你在看孤独的风景", artist: "单小源 & 本兮", src: "https://cdn-assets.bestelysia.com/火曜日/单小源、本兮 - 你在看孤独的风景【有间音乐】.wav", cover: "assets/nizaikangududefengjing .webp", lrc: "lyrics/你在看孤独的风景本兮单小源.lrc", category: "tue" },
    { title: "風鈴", artist: "蔣孜怡", src: "https://cdn-assets.bestelysia.com/火曜日/蔣孜怡-風鈴(FallingU中文版).mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/风铃蒋孜怡.lrc", category: "tue" },
    { title: "星晴", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/火曜日/周杰伦 - 星晴 + 回到过去 + 最后的战役 + 爱我别走 (Live).mp3", cover: "assets/xingqing.webp", lrc: "lyrics/星晴回到过去最后的战役爱我别走.lrc", category: "tue" },
    { title: "暗号", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/火曜日/周杰伦 - 暗号.flac", cover: "assets/anhao.webp", lrc: "lyrics/暗号周杰伦.lrc", category: "tue" },
    { title: "无限速", artist: "本兮 & 阿悄", src: "https://cdn-assets.bestelysia.com/火曜日/本兮&阿悄 - 无限速.flac", cover: "assets/wuxiansu.webp", lrc: "lyrics/无限速本兮阿悄.lrc", category: "tue" },
    { title: "心墙", artist: "林俊杰", src: "https://cdn-assets.bestelysia.com/火曜日/心墙.wav", cover: "assets/xinqiang.webp", lrc: "lyrics/心墙林俊杰.lrc", category: "tue" },
    { title: "听海", artist: "张惠妹", src: "https://cdn-assets.bestelysia.com/火曜日/张惠妹 - 听海.wav", cover: "assets/tinghai.webp", lrc: "lyrics/听海张惠妹.lrc", category: "tue" },
    { title: "处处吻", artist: "杨千嬅", src: "https://cdn-assets.bestelysia.com/火曜日/杨千嬅 - 处处吻.mp3", cover: "assets/ccw.webp", lrc: "lyrics/处处吻杨千嬅.lrc", category: "tue" },
    { title: "你不是真正的快乐", artist: "邓紫棋", src: "https://cdn-assets.bestelysia.com/火曜日/邓紫棋 - 你不是真正的快乐.wav", cover: "assets/nbszzdkl.webp", lrc: "lyrics/你不是真正的快乐Live邓紫棋.lrc", category: "tue" },
    { title: "一直很安静", artist: "阿桑", src: "https://cdn-assets.bestelysia.com/火曜日/阿桑 - 一直很安静.wav", cover: "assets/Elysia11.jpg", lrc: "lyrics/一直很安静阿桑.lrc", category: "tue" },
    { title: "珊瑚海", artist: "周杰倫 & 梁心颐", src: "https://cdn-assets.bestelysia.com/火曜日/周杰伦、梁心颐 - 珊瑚海.flac", cover: "assets/Elysia11.jpg", lrc: "lyrics/珊瑚海周杰伦Lara梁心颐.lrc", category: "tue" },
    { title: "怎么了", artist: "周杰倫 & 袁咏琳", src: "https://cdn-assets.bestelysia.com/火曜日/周杰伦;袁咏琳 - 怎么了.flac", cover: "assets/Elysia11.jpg", lrc: "lyrics/怎么了周杰伦袁咏琳.lrc", category: "tue" },
    { title: "花海", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/火曜日/周杰伦 - 花海.flac", cover: "assets/Elysia11.jpg", lrc: "lyrics/花海周杰伦.lrc", category: "tue" },
    { title: "爱在西元前", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/火曜日/周杰伦 - 爱在西元前 (Live).flac", cover: "assets/Elysia11.jpg", lrc: "lyrics/爱在西元前live.lrc", category: "tue" },
    
    { title: "清廉なるHeretics", artist: "毛蟹 feat.坂本真綾", src: "https://cdn-assets.bestelysia.com/月曜日/清廉なるHeretics.mp3", cover: "assets/ql.webp", lrc: "lyrics/清廉.lrc", category: "mon" },
    { title: "帝国少女", artist: "R Sound Design", src: "https://cdn-assets.bestelysia.com/月曜日/帝国少女.mp3", cover: "assets/dgsn.webp", lrc: "lyrics/帝国少女初音未来.lrc", category: "mon" },
    { title: "深海少女", artist: "Yuuyu-P", src: "https://cdn-assets.bestelysia.com/月曜日/深海少女.mp3", cover: "assets/shsn.webp", lrc: "lyrics/深海少女.lrc", category: "mon" },
    { title: "KISS OF DEATH", artist: "中島美嘉", src: "https://cdn-assets.bestelysia.com/月曜日/KISS OF DEATH.mp3", cover: "assets/kissofdeath.webp", lrc: "lyrics/KISS中岛美嘉.lrc", category: "mon" },
    { title: "月と花束さユり", artist: "酸欠少女さユり", src: "https://cdn-assets.bestelysia.com/月曜日/月と花束さユりSayuri.mp3", cover: "assets/yzsh.webp", lrc: "lyrics/月と花束月与花束.lrc", category: "mon" },
    { title: "自傷無色", artist: "Nekobolo", src: "https://cdn-assets.bestelysia.com/月曜日/自傷無色.mp3", cover: "assets/zsws.webp", lrc: "lyrics/自傷無色.lrc", category: "mon" },
    { title: "銀の龍の背に乗って", artist: "中島美雪", src: "https://cdn-assets.bestelysia.com/月曜日/中島美雪_ 銀の龍の背に乗って.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/銀の龍の背に乗って中岛美雪.lrc", category: "mon" },
    { title: "こころなし", artist: "Majiko", src: "https://cdn-assets.bestelysia.com/月曜日/いよ 酷いよもういっそ僕の體を.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/清廉.lrc", category: "mon" },
    { title: "再見只是陌生人", artist: "莊心妍", src: "https://cdn-assets.bestelysia.com/火曜日/再見只是陌生人.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/清廉.lrc", category: "tue" },
    { title: "如愿", artist: "王菲", src: "https://cdn-assets.bestelysia.com/火曜日/如愿.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/清廉.lrc", category: "tue" },
    { title: "爱我还是他", artist: "陶喆", src: "https://cdn-assets.bestelysia.com/火曜日/爱我还是他.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/清廉.lrc", category: "tue" },
    { title: "心生七面 善惡難辨", artist: "KBShinya", src: "https://cdn-assets.bestelysia.com/火曜日/心生七面善惡難辨.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/心生七面善恶难辨.lrc", category: "tue" },
    { title: "梦回还", artist: "呦貓UNEKO", src: "https://cdn-assets.bestelysia.com/火曜日/梦回还.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/清廉.lrc", category: "tue" },
    { title: "房間", artist: "刘瑞琦", src: "https://cdn-assets.bestelysia.com/火曜日/房間新版.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/清廉.lrc", category: "tue" },
    
    { title: "淪陷", artist: "王靖雯不胖", src: "https://cdn-assets.bestelysia.com/水曜日/淪陷.mp3", cover: "assets/lunxian.webp", lrc: "lyrics/沦陷.lrc", category: "wed" },
    { title: "羅生門 Follow", artist: "梨凍院", src: "https://cdn-assets.bestelysia.com/水曜日/羅生門Follow.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/罗生门Follow.lrc", category: "wed" },
    { title: "Reyi心跳的證明", artist: "劉人語", src: "https://cdn-assets.bestelysia.com/水曜日/Reyi心跳的證明電影.mp3", cover: "assets/xintiaodezhengming.webp", lrc: "lyrics/心跳的证明-刘人语.lrc", category: "wed" },
    { title: "裂縫中的陽光", artist: "林俊傑", src: "https://cdn-assets.bestelysia.com/水曜日/裂縫中的陽光.mp3", cover: "assets/liefengzhongdeyangguang.webp", lrc: "lyrics/裂缝中的阳光-林俊杰.lrc", category: "wed" },
    
    { title: "時空縫隙", artist: "苏星婕", src: "https://cdn-assets.bestelysia.com/日曜日/時空縫隙.mp3", cover: "assets/shikongfengxi.webp", lrc: "lyrics/时空缝隙.lrc", category: "sun" },
    { title: "日落的人海", artist: "小水", src: "https://cdn-assets.bestelysia.com/日曜日/日落的人海.mp3", cover: "assets/riluoderenhai.webp", lrc: "lyrics/日落的人海.lrc", category: "sun" },
    { title: "大概是我在说梦话", artist: "怪豆儿&KevinGee", src: "https://cdn-assets.bestelysia.com/日曜日/大概是我在说梦话.mp3", cover: "assets/dagaishiwozaishuomenghua.webp", lrc: "lyrics/大概是我在说梦话.lrc", category: "sun" },
    { title: "偏偏爱太重", artist: "徐健铭&细妹", src: "https://cdn-assets.bestelysia.com/日曜日/偏偏爱太重.mp3", cover: "assets/pianpianaitaizhong.webp", category: "sun" },
    { title: "心碎的声音", artist: "黑豆ADO", src: "https://cdn-assets.bestelysia.com/日曜日/Tiếnglòngvỡtan.mp3", cover: "assets/xinsuideshengyin.webp", category: "sun" },
    { title: "愛在深夜裡最難翻篇", artist: "en", src: "https://cdn-assets.bestelysia.com/日曜日/en愛在深夜裡最難翻篇.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "穿越时空", artist: "苏星婕", src: "assets/穿越时空.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/穿越时空星婕.lrc", category: "sun" },
    { title: "過分依賴", artist: "en", src: "https://cdn-assets.bestelysia.com/日曜日/en過分依賴.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "两相欢", artist: "音闕詩聽 & 昆玉", src: "https://cdn-assets.bestelysia.com/日曜日/两相欢音阙诗听昆玉.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "把遺憾還給你", artist: "以安", src: "https://cdn-assets.bestelysia.com/日曜日/以安把遺憾還給你.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "街角的晚风", artist: "励志豪 & 神勇尼尼", src: "https://cdn-assets.bestelysia.com/日曜日/励志豪神勇尼尼街角的晚风.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "舊情綿綿", artist: "半根蘿蔔", src: "https://cdn-assets.bestelysia.com/日曜日/半根蘿蔔舊情綿綿.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "红豆", artist: "卷笔刀阿卷", src: "https://cdn-assets.bestelysia.com/日曜日/卷笔刀阿卷红豆.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "和平分手", artist: "徐良 & 小暖", src: "https://cdn-assets.bestelysia.com/日曜日/和平分手徐良小暖.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "多远都要在一起", artist: "G.E.M.鄧紫棋", src: "https://cdn-assets.bestelysia.com/日曜日/多远都要在一起RnbbeatZxxy.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "后来遇见他", artist: "胡66", src: "https://cdn-assets.bestelysia.com/日曜日/大头针后来遇见他.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "春涧", artist: "大头针", src: "https://cdn-assets.bestelysia.com/日曜日/大头针春涧.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "情绪失控", artist: "季彦霖", src: "https://cdn-assets.bestelysia.com/日曜日/季彦霖情绪失控.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "定格", artist: "未知", src: "https://cdn-assets.bestelysia.com/日曜日/定格.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "怎麼會不遺憾呢", artist: "小兮橙", src: "https://cdn-assets.bestelysia.com/日曜日/小兮橙怎麼會不遺憾呢.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "流离", artist: "彭pini", src: "https://cdn-assets.bestelysia.com/日曜日/彭pini流离.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "就讓故事裡的人留在故事裡", artist: "拾三三", src: "https://cdn-assets.bestelysia.com/日曜日/拾三三就讓故事裡的人留在故事裡.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "故事還長", artist: "雲汐", src: "https://cdn-assets.bestelysia.com/日曜日/故事還長雲汐.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "明日坐标", artist: "林俊傑", src: "https://cdn-assets.bestelysia.com/日曜日/明日坐标王者荣耀十周年版本主题曲林俊杰王者荣耀.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "雨蝶", artist: "李翊君", src: "https://cdn-assets.bestelysia.com/日曜日/李翊君雨蝶.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "期許", artist: "燈叔", src: "https://cdn-assets.bestelysia.com/日曜日/燈叔期許.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "爱的故事上集", artist: "孙耀威", src: "https://cdn-assets.bestelysia.com/日曜日/爱的故事上集.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "他比我好吧", artist: "王理文", src: "https://cdn-assets.bestelysia.com/日曜日/王理文他比我好吧後來你遇見的他.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "他和她", artist: "耗子", src: "https://cdn-assets.bestelysia.com/日曜日/耗子他和她.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "沈园外", artist: "阿YueYue & 戾格", src: "https://cdn-assets.bestelysia.com/日曜日/阿YueYue戾格沈园外.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "等我不愛你", artist: "陳墨一 & 吖毛", src: "https://cdn-assets.bestelysia.com/日曜日/陳墨一吖毛等我不愛你我不再.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "漸冷", artist: "雪二", src: "https://cdn-assets.bestelysia.com/日曜日/雪二漸冷.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "願妳余生漫長", artist: "王貳浪", src: "https://cdn-assets.bestelysia.com/日曜日/願妳余生漫長王貳浪.mp3", cover: "assets/Elysia11.jpg", category: "sun" },
    { title: "风吹秋霜一地白", artist: "未知", src: "https://cdn-assets.bestelysia.com/日曜日/风吹秋霜一地白.mp3", cover: "assets/Elysia11.jpg", category: "sun" },

    { title: "PSYCHO-PASS 2 ED", artist: "EGOIST", src: "https://cdn-assets.bestelysia.com/月曜日/テレビアニメPSYCHO-PASS サイコパス 2エンディングテーマ.mp3", cover: "assets/Elysia11.jpg", category: "mon" },
    { title: "名前のない怪物", artist: "EGOIST", src: "https://cdn-assets.bestelysia.com/月曜日/名前のない怪物.mp3", cover: "assets/Elysia11.jpg", category: "mon" },
    { title: "See-Saw去り際のロマンティ", artist: "See-Saw", src: "https://cdn-assets.bestelysia.com/月曜日/See-Saw去り際のロマンティ.mp3", cover: "assets/Elysia11.jpg", category: "mon" },
    { title: "to the beginning", artist: "Kalafina", src: "https://cdn-assets.bestelysia.com/月曜日/tothebeginning.mp3", cover: "assets/Elysia11.jpg", category: "mon" },
    { title: "Zoetrope (AMNESIA OP)", artist: "Nagi Yanagi", src: "https://cdn-assets.bestelysia.com/月曜日/AMVアムネシアOPAMNESIA OPZoetrope.mp3", cover: "assets/Elysia11.jpg", category: "mon" }, 
    { title: "What is forever love", artist: "Lia", src: "https://cdn-assets.bestelysia.com/月曜日/Whatisforeverlove.mp3", cover: "https://cdn-assets.bestelysia.com/covers/whatisforeverlove.JPG", category: "mon" },
    { title: "The Way I Still Love You", artist: "Reyi", src: "https://cdn-assets.bestelysia.com/土曜日/ThewayIstillloveyou.mp3", cover: "assets/Elysia11.jpg", category: "sat" },
    { title: "会呼吸的痛", artist: "米塔", src: "https://cdn-assets.bestelysia.com/土曜日/MisideMitaAMVFullSong米塔の小曲会呼吸的痛-DJ.mp3", cover: "https://cdn-assets.bestelysia.com/covers/米诺.jpg", category: "sat" },
    { title: "珊瑚海 X One Last Time", artist: "Jay Chou x Ariana", src: "https://cdn-assets.bestelysia.com/土曜日/珊瑚海 X One Last Time(混响版).mp3", cover: "assets/Elysia11.jpg", category: "sat" },
    { title: "Angel", artist: "Yoon Mi Rae", src: "https://cdn-assets.bestelysia.com/水曜日/中字尹美莱Angel.mp3", cover: "assets/angel.webp", lrc: "lyrics/Angel尹美莱.lrc", category: "wed" },
    { title: "我只能離開", artist: "劉思達", src: "https://cdn-assets.bestelysia.com/水曜日/劉思達LOFTHESTAR我只能離開.mp3", cover: "assets/wozhinenglikai.webp", lrc: "lyrics/罗生门Follow.lrc", category: "wed" },
    { title: "橘子汽水", artist: "南拳媽媽", src: "https://cdn-assets.bestelysia.com/水曜日/南拳媽媽橘子汽水.mp3", cover: "assets/juziqishui.webp", lrc: "lyrics/橘子汽水-南拳妈妈.lrc", category: "wed" },
    { title: "園遊會", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/水曜日/周杰倫園遊會.mp3", cover: "assets/yuanyouhui.webp", lrc: "lyrics/园游会-周杰伦.lrc", category: "wed" },
    { title: "愛的飛行日記", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/水曜日/周杰倫愛的飛行日記.mp3", cover: "assets/aidefeixingriji.webp", lrc: "lyrics/爱的飞行日记.lrc", category: "wed" },
    { title: "遇到", artist: "方雅賢", src: "https://cdn-assets.bestelysia.com/水曜日/方雅賢遇到.mp3", cover: "assets/yudao.webp", lrc: "lyrics/遇到-方雅贤.lrc", category: "wed" },
    { title: "夏天", artist: "李玖哲", src: "https://cdn-assets.bestelysia.com/水曜日/李玖哲NickyLee夏天Summer-完整版MV.mp3", cover: "assets/xiatian.webp", lrc: "lyrics/夏天-李玖哲.lrc", category: "wed" },
    { title: "熱戀夏季", artist: "楊郡安", src: "https://cdn-assets.bestelysia.com/水曜日/楊郡安熱戀夏季.mp3", cover: "assets/relianxiaji.webp", lrc: "lyrics/热恋夏季-杨郡安.lrc", category: "wed" },
    { title: "夏天的风", artist: "温岚", src: "https://cdn-assets.bestelysia.com/水曜日/温岚夏天的风.mp3", cover: "assets/xiatiandefeng.webp", lrc: "lyrics/夏天的风-温岚.lrc", category: "wed" },
    { title: "全世界的人都知道", artist: "王俞勻", src: "https://cdn-assets.bestelysia.com/水曜日/王俞勻全世界的人都知道MV.mp3", cover: "assets/quanshijiederendouzhidao.webp", lrc: "lyrics/全世界的人都知道-王俞匀.lrc", category: "wed" },
    { title: "恶作剧", artist: "王蓝茵", src: "https://cdn-assets.bestelysia.com/水曜日/王蓝茵恶作剧.mp3", cover: "assets/ezuoju.webp", lrc: "lyrics/恶作剧-蓝心羽.lrc", category: "wed" },
    { title: "能不能", artist: "鐵竹堂 & 溫嵐", src: "https://cdn-assets.bestelysia.com/水曜日/能不能鐵竹堂&溫嵐.mp3", cover: "assets/nengbuneng.webp", lrc: "lyrics/能不能-温岚&JZN.lrc", category: "wed" },
    { title: "突然一場雨", artist: "藍心羽", src: "https://cdn-assets.bestelysia.com/水曜日/藍心羽突然一場雨.mp3", cover: "assets/turanyichangyu.webp", lrc: "lyrics/突然一场雨-蓝心羽.lrc", category: "wed" },
    { title: "直到你降臨我", artist: "阿肆", src: "https://cdn-assets.bestelysia.com/水曜日/阿肆直到你降臨我.mp3", cover: "assets/zhidaonijianglin.webp", lrc: "lyrics/直到你降临-阿肆.lrc", category: "wed" },
    { title: "其實你懂我", artist: "陳喬恩", src: "https://cdn-assets.bestelysia.com/水曜日/陳喬恩其實你懂我.mp3", cover: "assets/Elysia11.jpg", category: "wed" }, 
    { title: "光陰副本", artist: "林俊傑", src: "https://cdn-assets.bestelysia.com/水曜日/光陰副本.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/光阴副本.lrc", category: "wed" },
    { title: "在月蝕裡抱緊我", artist: "林俊傑", src: "https://cdn-assets.bestelysia.com/水曜日/林俊傑在月蝕裡抱緊我.flac", cover: "assets/Elysia11.jpg", lrc: "lyrics/在月蚀里抱紧我.lrc", category: "wed" }, 
    { title: "黑夜問白天", artist: "林俊傑", src: "https://cdn-assets.bestelysia.com/水曜日/林俊傑黑夜問白天.mp3", cover: "assets/Elysia11.jpg", lrc: "lyrics/黑夜问白天-林俊杰.lrc", category: "wed" },

    { title: "曹操", artist: "林俊傑", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/02. 曹操.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "黑色幽默", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/02. 黑色幽默.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "水仙", artist: "王心凌", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/03 水仙.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "不懂", artist: "林俊傑", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/03. 不懂.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "唯一", artist: "王力宏", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/03. 唯一.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "莎士比亚的天份", artist: "林俊傑", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/04. 莎士比亚的天份.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "江南", artist: "林俊傑", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/06. 江南.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "明天", artist: "吴克群", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/06. 明天.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "乌兰巴托的夜", artist: "鸿雁组合", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/09 乌兰巴托的夜--鸿雁组合(1).wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "简简单单", artist: "林俊傑", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/07. 简简单单.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "爱不会绝迹", artist: "林俊傑", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/09. 爱不会绝迹.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "转动", artist: "林俊傑", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/10. 转动.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "江南", artist: "林俊傑", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/12. 江南.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "终于等到你", artist: "孙露", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/12.终于等到你--孙露.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "她说", artist: "林俊傑", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/15. 她说.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "爱笑的眼睛", artist: "林俊傑", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/16. 爱笑的眼睛.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "one last time remix", artist: "Ariana Grande", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/one last time(remix).wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "友人說", artist: "林俊傑", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/友人說.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "不该 with aMEI", artist: "周杰倫 & 張惠妹", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 不该 (with aMEI) (《幻城》电视剧主题曲).flac", cover: "assets/Elysia11.jpg", lrc: "lyrics/不该withaMEI.lrc",  category: "unknown" },
    { title: "以父之名", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 以父之名 (Live).flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "你听得到", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 你听得到 (Live).flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "你怎么连话都说不清楚 live", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 你怎么连话都说不清楚 (Live).flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    
    { title: "半岛铁盒", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 半岛铁盒 (Live).flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "印第安老斑鸠", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 印第安老斑鸠.flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "反方向的钟", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 反方向的钟.flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "彩虹", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 彩虹.flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "开不了口 live", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 开不了口 (Live).flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "夜曲", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 夜曲.flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "手写的从前", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 手写的从前.flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "搁浅 live", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 搁浅 (Live).flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "借口", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 借口.flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "枫", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 枫.flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "白色风车", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 白色风车.flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "给我一首歌的时间", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 给我一首歌的时间.flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "稻香", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 稻香.flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "蒲公英的约定", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 蒲公英的约定.flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "说好的幸福呢", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 说好的幸福呢＋淘汰＋青花瓷 (Live).flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "超人不会飞", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 超人不会飞.flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "退后", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 退后.flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "逆鳞", artist: "周杰倫", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦 - 逆鳞.flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "爱的飞行日记", artist: "周杰倫 & 杨瑞代", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦;杨瑞代 - 爱的飞行日记.flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "等你下课", artist: "周杰倫 & 杨瑞代", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦&杨瑞代 - 等你下课.mp3", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "给我一首歌的时间 live", artist: "周杰倫 & 蔡依林", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/周杰伦;蔡依林 - 给我一首歌的时间(live).mp3", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "爱笑的眼睛", artist: "徐若瑄", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/爱笑的眼睛.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "我可以抱你吗", artist: "张惠妹", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/张惠妹 - 我可以抱你吗.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "我很想爱他", artist: "Twins", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/我很想爱他.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "慢慢喜欢你", artist: "莫文蔚", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/莫文慰 - 慢慢喜欢你.flac", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "阴天", artist: "莫文蔚", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/莫文蔚 - 阴天【有间音乐】.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "寂寞在唱歌", artist: "阿桑", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/阿桑 - 寂寞在唱歌.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "K歌之王", artist: "陈奕迅", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/陈奕迅 - K歌之王粤语【有间音乐】.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "莫失莫忘", artist: "阿桑", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/阿桑 - 莫失莫忘.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
    { title: "零度的親吻", artist: "林俊傑", src: "https://cdn-assets.bestelysia.com/暂时想不到名字所以只能这样/零度的親吻.wav", cover: "assets/Elysia11.jpg", category: "unknown" },
     

  { title: "嗵嗵", artist: "DOU", src: "https://cdn-assets.bestelysia.com/金曜日/DOU嗵嗵.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "不要慌太阳下山有月光", artist: "GooGoo", src: "https://cdn-assets.bestelysia.com/金曜日/GooGoo不要慌太阳下山有月光.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "壁上观", artist: "一棵小葱/张晓涵", src: "https://cdn-assets.bestelysia.com/金曜日/一棵小葱张晓涵壁上观.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "消散对白", artist: "丁禹兮", src: "https://cdn-assets.bestelysia.com/金曜日/丁禹兮消散对白.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "明明深爱着你", artist: "丁肆Dicey", src: "https://cdn-assets.bestelysia.com/金曜日/丁肆Dicey明明深爱着你.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "其实都没有", artist: "于冬然", src: "https://cdn-assets.bestelysia.com/金曜日/于冬然其实都没有.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "亲爱的你啊", artist: "任素汐", src: "https://cdn-assets.bestelysia.com/金曜日/任素汐亲爱的你啊.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "你看你看月亮的脸", artist: "大头针", src: "https://cdn-assets.bestelysia.com/金曜日/你看你看月亮的脸大头针.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "土坡上的狗尾草", artist: "卢润泽", src: "https://cdn-assets.bestelysia.com/金曜日/卢润泽土坡上的狗尾草.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "暮色回响", artist: "吉星出租", src: "https://cdn-assets.bestelysia.com/金曜日/吉星出租暮色回响.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "我想要占据你", artist: "告五人", src: "https://cdn-assets.bestelysia.com/金曜日/告五人我想要占据你.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "青花", artist: "周传雄", src: "https://cdn-assets.bestelysia.com/金曜日/周传雄青花.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "阿嬷爱国版", artist: "周林枫", src: "https://cdn-assets.bestelysia.com/金曜日/周林枫阿嬷爱国版.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "小美满", artist: "周深", src: "https://cdn-assets.bestelysia.com/金曜日/周深小美满.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "街角的晚风", artist: "善宇", src: "https://cdn-assets.bestelysia.com/金曜日/善宇怪兽街角的晚风.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "天亮以前说再见", artist: "四熹丸子", src: "https://cdn-assets.bestelysia.com/金曜日/四熹丸子天亮以前说再见.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "妥协", artist: "群星", src: "https://cdn-assets.bestelysia.com/金曜日/妥协.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "两三句", artist: "宋佳", src: "https://cdn-assets.bestelysia.com/金曜日/宋佳野两三句.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "哩哩执子之手", artist: "宝石Gem", src: "https://cdn-assets.bestelysia.com/金曜日/宝石Gem哩哩执子之手.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "离别开出花", artist: "就是南方凯", src: "https://cdn-assets.bestelysia.com/金曜日/就是南方凯离别开出花.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "我期待的不是雪", artist: "张妙格", src: "https://cdn-assets.bestelysia.com/金曜日/张妙格我期待的不是雪.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "无名的人", artist: "张韶涵", src: "https://cdn-assets.bestelysia.com/金曜日/张韶涵无名的人.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "身骑白马", artist: "徐佳莹", src: "https://cdn-assets.bestelysia.com/金曜日/徐佳莹身骑白马.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "爱你", artist: "徐俊雅", src: "https://cdn-assets.bestelysia.com/金曜日/徐俊雅爱你.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "面具", artist: "徐薇", src: "https://cdn-assets.bestelysia.com/金曜日/徐薇面具.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "望故乡", artist: "文夫", src: "https://cdn-assets.bestelysia.com/金曜日/文夫望故乡.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "背着风流泪", artist: "文夫", src: "https://cdn-assets.bestelysia.com/金曜日/文夫背着风流泪.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "特别的人", artist: "方大同", src: "https://cdn-assets.bestelysia.com/金曜日/方大同特别的人.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "青丝", artist: "时光胶囊", src: "https://cdn-assets.bestelysia.com/金曜日/时光胶囊青丝.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "只为你着迷", artist: "李秉成", src: "https://cdn-assets.bestelysia.com/金曜日/李秉成只为你着迷.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "恋人", artist: "李荣浩", src: "https://cdn-assets.bestelysia.com/金曜日/李荣浩恋人.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "西楼爱情故事", artist: "李袁杰Au", src: "https://cdn-assets.bestelysia.com/金曜日/李袁杰Au西楼爱情故事.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "无名的人", artist: "毛不易", src: "https://cdn-assets.bestelysia.com/金曜日/毛不易无名的人.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "最后一页", artist: "江语晨", src: "https://cdn-assets.bestelysia.com/金曜日/江语晨最后一页.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "谁", artist: "洋澜", src: "https://cdn-assets.bestelysia.com/金曜日/洋澜谁.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "西楼儿女", artist: "海来阿木", src: "https://cdn-assets.bestelysia.com/金曜日/海来阿木西楼儿女.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "苹果香", artist: "狼戈", src: "https://cdn-assets.bestelysia.com/金曜日/狼戈苹果香.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "爱错", artist: "王力宏", src: "https://cdn-assets.bestelysia.com/金曜日/王力宏爱错.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "舍得", artist: "王唯旖", src: "https://cdn-assets.bestelysia.com/金曜日/王唯旖舍得.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "月亮翻过小山坡", artist: "王海颖,孙圳翰", src: "https://cdn-assets.bestelysia.com/金曜日/王海颖,孙圳翰 - 月亮翻过小山坡.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "大山", artist: "王睿卓", src: "https://cdn-assets.bestelysia.com/金曜日/王睿卓大山.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "重生之我在异乡为异客", artist: "王睿卓", src: "https://cdn-assets.bestelysia.com/金曜日/王睿卓重生之我在异乡为异客.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "离开我的依赖", artist: "王艳薇", src: "https://cdn-assets.bestelysia.com/金曜日/王艳薇离开我的依赖.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "先说爱的人为什么先离开", artist: "田园", src: "https://cdn-assets.bestelysia.com/金曜日/田园先说爱的人为什么先离开.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "白鸽乌鸦相爱的戏码", artist: "皮卡潘", src: "https://cdn-assets.bestelysia.com/金曜日/皮卡潘白鸽乌鸦相爱的戏码.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "月亮照山川", artist: "窝窝", src: "https://cdn-assets.bestelysia.com/金曜日/窝窝月亮照山川.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "到时说爱我", artist: "茜拉", src: "https://cdn-assets.bestelysia.com/金曜日/茜拉到时说爱我.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "第57次取消发送", artist: "菲菲公主/陆绮菲", src: "https://cdn-assets.bestelysia.com/金曜日/菲菲公主陆绮菲第57次取消发送.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "别无所爱", artist: "袁小葳KyL3", src: "https://cdn-assets.bestelysia.com/金曜日/袁小葳KyL3别无所爱.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "唯一", artist: "邓紫棋", src: "https://cdn-assets.bestelysia.com/金曜日/邓紫棋唯一.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "须尽欢", artist: "郑浩", src: "https://cdn-assets.bestelysia.com/金曜日/郑浩须尽欢.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "瞬", artist: "郑润泽", src: "https://cdn-assets.bestelysia.com/金曜日/郑润泽瞬.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "诺言", artist: "郭有才", src: "https://cdn-assets.bestelysia.com/金曜日/郭有才诺言 .mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "爱情讯息", artist: "郭静", src: "https://cdn-assets.bestelysia.com/金曜日/郭静爱情讯息.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "一笑江湖", artist: "闻人听書", src: "https://cdn-assets.bestelysia.com/金曜日/闻人听書一笑江湖.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "如果可以", artist: "韦礼安", src: "https://cdn-assets.bestelysia.com/金曜日/韦礼安如果可以.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "搀扶", artist: "马健涛", src: "https://cdn-assets.bestelysia.com/金曜日/马健涛搀扶.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "我们的明天", artist: "鹿晗", src: "https://cdn-assets.bestelysia.com/金曜日/鹿晗我们的明天.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
    
  { title: "Mood (Lil Ghost Remix_Explicit)", artist: "24KGoldn/iann dior/Lil Ghost小鬼", src: "https://cdn-assets.bestelysia.com/金曜日/24KGoldn _ iann dior _ Lil Ghost小鬼 - Mood (Lil Ghost Remix_Explicit).mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "精卫", artist: "30年前，50年后", src: "https://cdn-assets.bestelysia.com/金曜日/30年前，50年后 - 精卫.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "一半疯了一半算了", artist: "3秒超市", src: "https://cdn-assets.bestelysia.com/金曜日/3秒超市 - 一半疯了一半算了.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "天若有情", artist: "A-Lin", src: "https://cdn-assets.bestelysia.com/金曜日/A-Lin - 天若有情.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "Butterfly", artist: "A1 TRIP/Nick_Y", src: "https://cdn-assets.bestelysia.com/金曜日/A1 TRIP _ Nick_Y - Butterfly.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "Aloha Heja He", artist: "Achim Reichel", src: "https://cdn-assets.bestelysia.com/金曜日/Achim Reichel - Aloha Heja He.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "Easy On Me", artist: "Adele", src: "https://cdn-assets.bestelysia.com/金曜日/Adele - Easy On Me.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "22秒", artist: "Aioz", src: "https://cdn-assets.bestelysia.com/金曜日/Aioz - 22秒.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "봄여름가을겨울 (Still Life)", artist: "BIGBANG", src: "https://cdn-assets.bestelysia.com/金曜日/BIGBANG-봄여름가을겨울 (Still Life).mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "雪 Distance", artist: "Capper/罗言", src: "https://cdn-assets.bestelysia.com/金曜日/Capper,罗言 - 雪 Distance.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "风吹一夏", artist: "DP龙猪/Swei水/Rays陈袁", src: "https://cdn-assets.bestelysia.com/金曜日/DP龙猪,Swei水,Rays陈袁 - 风吹一夏.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "Free Loop", artist: "Daniel Powter", src: "https://cdn-assets.bestelysia.com/金曜日/Daniel Powter-Free Loop.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "离开你以后", artist: "Eric周兴哲", src: "https://cdn-assets.bestelysia.com/金曜日/Eric周兴哲 - 离开你以后.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "桃花诺", artist: "G.E.M.邓紫棋", src: "https://cdn-assets.bestelysia.com/金曜日/G.E.M.邓紫棋-桃花诺-《上古情歌》电视剧片尾曲.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "多远都要在一起", artist: "G.E.M. 邓紫棋", src: "https://cdn-assets.bestelysia.com/金曜日/G_E_M_ 邓紫棋 - 多远都要在一起.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "无双的王者", artist: "G.E.M. 邓紫棋/王者荣耀", src: "https://cdn-assets.bestelysia.com/金曜日/G_E_M_ 邓紫棋 _ 王者荣耀 - 无双的王者.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "落日与晚风", artist: "IN-K/王忻辰/苏星婕", src: "https://cdn-assets.bestelysia.com/金曜日/IN-K_王忻辰_苏星婕-落日与晚风.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "ELEVEN", artist: "IVE", src: "https://cdn-assets.bestelysia.com/金曜日/IVE - ELEVEN.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "Power (In Your Soul)", artist: "Interupt/Luna LePage", src: "https://cdn-assets.bestelysia.com/金曜日/Interupt _ Luna LePage - Power (In Your Soul).mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "若把你", artist: "Kirsty刘瑾睿", src: "https://cdn-assets.bestelysia.com/金曜日/Kirsty刘瑾睿 - 若把你.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "小城夏天", artist: "LBI利比", src: "https://cdn-assets.bestelysia.com/金曜日/LBI利比 - 小城夏天.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "满目星辰皆是你", artist: "LKer林柯", src: "https://cdn-assets.bestelysia.com/金曜日/LKer林柯 - 满目星辰皆是你.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "不良少年", artist: "Lil Ghost小鬼", src: "https://cdn-assets.bestelysia.com/金曜日/Lil Ghost小鬼 - 不良少年.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "别叫我达芬奇 (Punk Version)", artist: "Lil Ghost小鬼", src: "https://cdn-assets.bestelysia.com/金曜日/Lil Ghost小鬼 - 别叫我达芬奇 (Punk Version).mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "暖灰", artist: "Li仔", src: "https://cdn-assets.bestelysia.com/金曜日/Li仔 - 暖灰.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "花,太阳,彩虹,你", artist: "Mai/法老/肯迪仔", src: "https://cdn-assets.bestelysia.com/金曜日/Mai,法老,肯迪仔 - 花,太阳,彩虹,你.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "ไม่ได้ก็ไม่เอาWhatever", artist: "Pixxie/Zom Marie", src: "https://cdn-assets.bestelysia.com/金曜日/Pixxie_Zom Marieไม่ได้ก็ไม่เอาWhatever.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "Dễ Đến Dễ Đi", artist: "Quang Hùng MasterD", src: "https://cdn-assets.bestelysia.com/金曜日/Quang Hùng MasterD-Dễ Đến Dễ Đi.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "Find Me", artist: "R1SE", src: "https://cdn-assets.bestelysia.com/金曜日/R1SE - Find Me.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "すずめ feat.十明", artist: "RADWIMPS/十明", src: "https://cdn-assets.bestelysia.com/金曜日/RADWIMPS,十明 - すずめ feat.十明.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "Ring Ring Ring", artist: "S.H.E", src: "https://cdn-assets.bestelysia.com/金曜日/S_H_E - Ring Ring Ring.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "Stitches", artist: "Shawn Mendes", src: "https://cdn-assets.bestelysia.com/金曜日/Shawn Mendes - Stitches.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "苦茶子", artist: "Starling8/MoreLearn 27/FIVESTAR", src: "https://cdn-assets.bestelysia.com/金曜日/Starling8,MoreLearn 27,FIVESTAR - 苦茶子.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "三国恋", artist: "Tank", src: "https://cdn-assets.bestelysia.com/金曜日/Tank - 三国恋.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "Stay (Explicit)", artist: "The Kid LAROI/Justin Bieber", src: "https://cdn-assets.bestelysia.com/金曜日/The Kid LAROI _ Justin Bieber - Stay (Explicit).mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "少数派报告", artist: "Tizzy T/VaVa毛衍七/Jony J", src: "https://cdn-assets.bestelysia.com/金曜日/Tizzy T _ VaVa毛衍七 _ Jony J _ 布瑞吉Bridge _ 黄旭 - 少数派报告.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "Dạ Vũ（夜舞）", artist: "Tăng Duy Tân/BAE", src: "https://cdn-assets.bestelysia.com/金曜日/Tăng Duy Tân _ BAE - Dạ Vũ（夜舞）.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "小城小爱", artist: "Uu", src: "https://cdn-assets.bestelysia.com/金曜日/Uu-小城小爱.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "Bet On Me", artist: "Walk off the Earth/D Smoke", src: "https://cdn-assets.bestelysia.com/金曜日/Walk off the Earth,D Smoke - Bet On Me.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "You and I", artist: "Will Armex/Katy M", src: "https://cdn-assets.bestelysia.com/金曜日/Will Armex _ Katy M - You and I.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "堕", artist: "Zyboy忠宇", src: "https://cdn-assets.bestelysia.com/金曜日/Zyboy忠宇 - 堕.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "妈妈的话", artist: "Zyboy忠宇", src: "https://cdn-assets.bestelysia.com/金曜日/Zyboy忠宇 - 妈妈的话.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "Next Level", artist: "aespa (에스파)", src: "https://cdn-assets.bestelysia.com/金曜日/aespa (에스파)-Next Level.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "忘不掉的你", artist: "h3R3", src: "https://cdn-assets.bestelysia.com/金曜日/h3R3 - 忘不掉的你.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "等不来花开", artist: "pro", src: "https://cdn-assets.bestelysia.com/金曜日/pro等不来花开.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "0321", artist: "space x", src: "https://cdn-assets.bestelysia.com/金曜日/space x-0321.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "满天星辰不及你", artist: "ycccc", src: "https://cdn-assets.bestelysia.com/金曜日/ycccc - 满天星辰不及你.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "致你", artist: "yihuik苡慧", src: "https://cdn-assets.bestelysia.com/金曜日/yihuik苡慧 - 致你.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "麦浪", artist: "yihuik苡慧", src: "https://cdn-assets.bestelysia.com/金曜日/yihuik苡慧 - 麦浪.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "罗刹海市", artist: "刀郎", src: "https://cdn-assets.bestelysia.com/金曜日/刀郎 - 罗刹海市.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "花妖", artist: "刀郎", src: "https://cdn-assets.bestelysia.com/金曜日/刀郎 - 花妖.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "放空", artist: "大籽/Lil E", src: "https://cdn-assets.bestelysia.com/金曜日/大籽,Lil E - 放空.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "潮汐(Natural)", artist: "安苏羽/傅梦彤", src: "https://cdn-assets.bestelysia.com/金曜日/安苏羽 _ 傅梦彤 - 潮汐(Natural).mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "电梯战神", artist: "宝石Gem", src: "https://cdn-assets.bestelysia.com/金曜日/宝石Gem - 电梯战神.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "下潜", artist: "川青/Morerare", src: "https://cdn-assets.bestelysia.com/金曜日/川青 _ Morerare - 下潜.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "我会等", artist: "承桓", src: "https://cdn-assets.bestelysia.com/金曜日/承桓-我会等.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "爱丫爱丫", artist: "By2", src: "https://cdn-assets.bestelysia.com/金曜日/爱丫爱丫 - By2.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "往后余生只爱你", artist: "白小白", src: "https://cdn-assets.bestelysia.com/金曜日/白小白 - 往后余生只爱你.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "外婆说", artist: "程jiajia", src: "https://cdn-assets.bestelysia.com/金曜日/程jiajia - 外婆说.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "好想抱住你", artist: "程jiajia", src: "https://cdn-assets.bestelysia.com/金曜日/程jiajia - 好想抱住你.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "山楂树の恋", artist: "程jiajia", src: "https://cdn-assets.bestelysia.com/金曜日/程jiajia - 山楂树の恋.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "爱是无畏的冒险", artist: "程今", src: "https://cdn-assets.bestelysia.com/金曜日/程今 - 爱是无畏的冒险.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "可能", artist: "程响", src: "https://cdn-assets.bestelysia.com/金曜日/程响 - 可能.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "时光洪流", artist: "程响", src: "https://cdn-assets.bestelysia.com/金曜日/程响 - 时光洪流.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "踏雪", artist: "等什么君(邓寓君)/FOX胡天渝", src: "https://cdn-assets.bestelysia.com/金曜日/等什么君(邓寓君) _ FOX胡天渝 - 踏雪.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "Letting Go", artist: "蔡健雅", src: "https://cdn-assets.bestelysia.com/金曜日/蔡健雅 - Letting Go.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "读你", artist: "蔡琴", src: "https://cdn-assets.bestelysia.com/金曜日/蔡琴-读你.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "我太笨", artist: "锤娜丽莎", src: "https://cdn-assets.bestelysia.com/金曜日/锤娜丽莎 - 我太笨.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "不负人间", artist: "阿YueYue", src: "https://cdn-assets.bestelysia.com/金曜日/阿YueYue - 不负人间.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "未发送", artist: "阿冗", src: "https://cdn-assets.bestelysia.com/金曜日/阿冗 -未发送.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "阿衣莫", artist: "阿吉太组合", src: "https://cdn-assets.bestelysia.com/金曜日/阿吉太组合 - 阿衣莫.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "晚风心里吹", artist: "阿梨粤", src: "https://cdn-assets.bestelysia.com/金曜日/阿梨粤 - 晚风心里吹.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "秒针 (Dj版)", artist: "阿梨粤", src: "https://cdn-assets.bestelysia.com/金曜日/阿梨粤DJR7秒针Dj版.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "热爱105°C的你", artist: "阿肆", src: "https://cdn-assets.bestelysia.com/金曜日/阿肆 - 热爱105°C的你.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "孤勇者", artist: "陈奕迅", src: "https://cdn-assets.bestelysia.com/金曜日/陈奕迅 - 孤勇者.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "陪你看星星", artist: "陈子晴", src: "https://cdn-assets.bestelysia.com/金曜日/陈子晴 - 陪你看星星.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "孤独颂歌", artist: "陈文非", src: "https://cdn-assets.bestelysia.com/金曜日/陈文非 - 孤独颂歌.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "死性不改", artist: "陈柯霓 (CHENge)", src: "https://cdn-assets.bestelysia.com/金曜日/陈柯霓 (CHENge) - 死性不改.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "下辈子不一定还能遇见你", artist: "陈雅森", src: "https://cdn-assets.bestelysia.com/金曜日/陈雅森 - 下辈子不一定还能遇见你.mp3", cover: "assets/Elysia11.jpg", category: "fri" },


  { title: "香水有毒 (七喜版)", artist: "七喜", src: "https://cdn-assets.bestelysia.com/金曜日/七喜 - 香水有毒 (七喜版).mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "骁", artist: "井胧/井迪儿", src: "https://cdn-assets.bestelysia.com/金曜日/井胧_井迪儿-骁.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "金玉良缘", artist: "付雪", src: "https://cdn-assets.bestelysia.com/金曜日/付雪 - 金玉良缘.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "如一", artist: "任嘉伦", src: "https://cdn-assets.bestelysia.com/金曜日/任嘉伦 - 如一.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "一去不回的时光", artist: "任然", src: "https://cdn-assets.bestelysia.com/金曜日/任然 - 一去不回的时光.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "雀跃", artist: "任然", src: "https://cdn-assets.bestelysia.com/金曜日/任然 - 雀跃.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "时光采样 (钢琴版)", artist: "伏仪", src: "https://cdn-assets.bestelysia.com/金曜日/伏仪 - 时光采样 (钢琴版).mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "白鸽", artist: "你的上好佳", src: "https://cdn-assets.bestelysia.com/金曜日/你的上好佳 - 白鸽.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "提笔忘情", artist: "关心", src: "https://cdn-assets.bestelysia.com/金曜日/关心 - 提笔忘情.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "奢香夫人", artist: "凤凰传奇", src: "https://cdn-assets.bestelysia.com/金曜日/凤凰传奇 - 奢香夫人.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "假装 (吉他版)", artist: "刘大壮", src: "https://cdn-assets.bestelysia.com/金曜日/刘大壮 - 假装 (吉他版).mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "吉他初恋", artist: "刘大壮", src: "https://cdn-assets.bestelysia.com/金曜日/刘大壮 - 吉他初恋.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "再见莫妮卡", artist: "刘大拿/褚晨茜", src: "https://cdn-assets.bestelysia.com/金曜日/刘大拿,褚晨茜 - 再见莫妮卡.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "Got You", artist: "刘耀文", src: "https://cdn-assets.bestelysia.com/金曜日/刘耀文 - Got You.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "鲸语", artist: "刘至佳", src: "https://cdn-assets.bestelysia.com/金曜日/刘至佳 - 鲸语.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "时光背面的我", artist: "刘至佳/韩瞳", src: "https://cdn-assets.bestelysia.com/金曜日/刘至佳_韩瞳-时光背面的我.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "听闻远方有你", artist: "刘艺雯", src: "https://cdn-assets.bestelysia.com/金曜日/刘艺雯 - 听闻远方有你.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "与你到永久", artist: "南瓜", src: "https://cdn-assets.bestelysia.com/金曜日/南瓜 - 与你到永久.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "阳光开朗大男孩", artist: "卦者灵风", src: "https://cdn-assets.bestelysia.com/金曜日/卦者灵风 - 阳光开朗大男孩.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "必杀技", artist: "古巨基", src: "https://cdn-assets.bestelysia.com/金曜日/古巨基 - 必杀技.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "失忆 (正式版)", artist: "吕口口", src: "https://cdn-assets.bestelysia.com/金曜日/吕口口 - 失忆 (正式版).mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "唯一", artist: "告五人", src: "https://cdn-assets.bestelysia.com/金曜日/告五人 - 唯一.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "带我去找夜生活", artist: "告五人", src: "https://cdn-assets.bestelysia.com/金曜日/告五人 - 带我去找夜生活.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "给你一瓶魔法药水", artist: "告五人", src: "https://cdn-assets.bestelysia.com/金曜日/告五人 - 给你一瓶魔法药水.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "初恋", artist: "回春丹", src: "https://cdn-assets.bestelysia.com/金曜日/回春丹 - 初恋.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "问心", artist: "就是南方凯", src: "https://cdn-assets.bestelysia.com/金曜日/就是南方凯 - 问心.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "你永远是我的宝贝，宝贝", artist: "康姆士COM'Z", src: "https://cdn-assets.bestelysia.com/金曜日/康姆士COM'Z - 你永远是我的宝贝，宝贝.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "星星永远发着光", artist: "彭宇昕Chloe", src: "https://cdn-assets.bestelysia.com/金曜日/彭宇昕Chloe - 星星永远发着光.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "语病", artist: "彭小胖", src: "https://cdn-assets.bestelysia.com/金曜日/彭小胖 - 语病.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "再见莫妮卡", artist: "彭席彦/Franky弗兰奇", src: "https://cdn-assets.bestelysia.com/金曜日/彭席彦,Franky弗兰奇 - 再见莫妮卡.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "如果爱忘了", artist: "戚薇", src: "https://cdn-assets.bestelysia.com/金曜日/戚薇 - 如果爱忘了.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "New Boy", artist: "房东的猫/陈婧霏", src: "https://cdn-assets.bestelysia.com/金曜日/房东的猫,陈婧霏 - New Boy.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "烟火星辰", artist: "摩登兄弟刘宇宁", src: "https://cdn-assets.bestelysia.com/金曜日/摩登兄弟刘宇宁 - 烟火星辰.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "特别的人", artist: "方大同", src: "https://cdn-assets.bestelysia.com/金曜日/方大同 - 特别的人.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "谁", artist: "曲肖冰", src: "https://cdn-assets.bestelysia.com/金曜日/曲肖冰-谁.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "鲸落", artist: "李小璐", src: "https://cdn-assets.bestelysia.com/金曜日/李小璐 - 鲸落.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "氧化氢", artist: "李尖尖", src: "https://cdn-assets.bestelysia.com/金曜日/李尖尖 - 氧化氢.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "守护着我的光", artist: "李巍", src: "https://cdn-assets.bestelysia.com/金曜日/李巍-守护着我的光.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "爱丫爱丫", artist: "李浩然", src: "https://cdn-assets.bestelysia.com/金曜日/李浩然 - 爱丫爱丫.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "万疆", artist: "李玉刚", src: "https://cdn-assets.bestelysia.com/金曜日/李玉刚 - 万疆.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "不遗憾", artist: "李荣浩", src: "https://cdn-assets.bestelysia.com/金曜日/李荣浩 - 不遗憾.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "乌梅子酱", artist: "李荣浩", src: "https://cdn-assets.bestelysia.com/金曜日/李荣浩 - 乌梅子酱.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "原来我从未忘记你", artist: "杜宣达", src: "https://cdn-assets.bestelysia.com/金曜日/杜宣达 - 原来我从未忘记你.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "指纹", artist: "杜宣达", src: "https://cdn-assets.bestelysia.com/金曜日/杜宣达 - 指纹.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "解药 (新版)", artist: "来一碗老于", src: "https://cdn-assets.bestelysia.com/金曜日/来一碗老于 - 解药 (新版).mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "新地球", artist: "林俊杰", src: "https://cdn-assets.bestelysia.com/金曜日/林俊杰 - 新地球.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "姑娘在远方", artist: "柯柯柯啊", src: "https://cdn-assets.bestelysia.com/金曜日/柯柯柯啊 - 姑娘在远方.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "总以为来日方长", artist: "梅朵", src: "https://cdn-assets.bestelysia.com/金曜日/梅朵 - 总以为来日方长.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "是你", artist: "梦然", src: "https://cdn-assets.bestelysia.com/金曜日/梦然 - 是你.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "罗生门（Follow）", artist: "梨冻紧/Wiz_H张子豪", src: "https://cdn-assets.bestelysia.com/金曜日/梨冻紧,Wiz_H张子豪 - 罗生门（Follow）.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "特别邀请", artist: "橘子妹", src: "https://cdn-assets.bestelysia.com/金曜日/橘子妹 - 特别邀请.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "如你所想", artist: "毛不易", src: "https://cdn-assets.bestelysia.com/金曜日/毛不易 - 如你所想.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "孤城", artist: "洛先生", src: "https://cdn-assets.bestelysia.com/金曜日/洛先生 - 孤城.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "影子说", artist: "洛先生", src: "https://cdn-assets.bestelysia.com/金曜日/洛先生 - 影子说.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "年少的你啊", artist: "浩然H.R", src: "https://cdn-assets.bestelysia.com/金曜日/浩然H.R - 年少的你啊.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "画离弦", artist: "海伦", src: "https://cdn-assets.bestelysia.com/金曜日/海伦 - 画离弦.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "三生三幸", artist: "海来阿木", src: "https://cdn-assets.bestelysia.com/金曜日/海来阿木 - 三生三幸.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "五十年以后", artist: "海来阿木", src: "https://cdn-assets.bestelysia.com/金曜日/海来阿木 - 五十年以后.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "烟雨人间", artist: "海来阿木", src: "https://cdn-assets.bestelysia.com/金曜日/海来阿木 - 烟雨人间.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "我的美丽feat.海洋Bo", artist: "海洋Bo/高睿", src: "https://cdn-assets.bestelysia.com/金曜日/海洋Bo,高睿 - 我的美丽feat.海洋Bo.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "须尽欢", artist: "渡", src: "https://cdn-assets.bestelysia.com/金曜日/渡 - 须尽欢.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "以爱为囚", artist: "满舒克", src: "https://cdn-assets.bestelysia.com/金曜日/满舒克 - 以爱为囚.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "我想要", artist: "盖君炎", src: "https://cdn-assets.bestelysia.com/金曜日/盖君炎 - 我想要.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "不如", artist: "秦海清", src: "https://cdn-assets.bestelysia.com/金曜日/秦海清 - 不如.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "自愈", artist: "穆哲熙", src: "https://cdn-assets.bestelysia.com/金曜日/穆哲熙 - 自愈.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "命运", artist: "粉太狼", src: "https://cdn-assets.bestelysia.com/金曜日/粉太狼 - 命运.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "下辈子不一定还能遇见你 (吉他版)", artist: "莫叫姐姐", src: "https://cdn-assets.bestelysia.com/金曜日/莫叫姐姐 - 下辈子不一定还能遇见你 (吉他版).mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "不该用情 (女声版)", artist: "莫叫姐姐", src: "https://cdn-assets.bestelysia.com/金曜日/莫叫姐姐 - 不该用情 (女声版).mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "你能不能不要离开我", artist: "莫叫姐姐", src: "https://cdn-assets.bestelysia.com/金曜日/莫叫姐姐 - 你能不能不要离开我.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "当我娶过她", artist: "莫叫姐姐", src: "https://cdn-assets.bestelysia.com/金曜日/莫叫姐姐 - 当我娶过她.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "风中有朵雨做的云 (粤语莫叫语版)", artist: "莫叫姐姐", src: "https://cdn-assets.bestelysia.com/金曜日/莫叫姐姐 - 风中有朵雨做的云 (粤语莫叫语版).mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "这世界那么多人", artist: "莫文蔚", src: "https://cdn-assets.bestelysia.com/金曜日/莫文蔚 - 这世界那么多人.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "悬溺", artist: "葛东琪", src: "https://cdn-assets.bestelysia.com/金曜日/葛东琪 - 悬溺.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "几里之外", artist: "董嘉鸿", src: "https://cdn-assets.bestelysia.com/金曜日/董嘉鸿 - 几里之外.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "漫步宇宙", artist: "蓝心羽", src: "https://cdn-assets.bestelysia.com/金曜日/蓝心羽 - 漫步宇宙.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "寂寞烟火", artist: "蓝心羽", src: "https://cdn-assets.bestelysia.com/金曜日/蓝心羽-寂寞烟火.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "星辰不坠落", artist: "蓝心羽", src: "https://cdn-assets.bestelysia.com/金曜日/蓝心羽-星辰不坠落.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "窗", artist: "虎二", src: "https://cdn-assets.bestelysia.com/金曜日/虎二 - 窗.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "太想念", artist: "豆包", src: "https://cdn-assets.bestelysia.com/金曜日/豆包 - 太想念.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "你的", artist: "贺仙人", src: "https://cdn-assets.bestelysia.com/金曜日/贺仙人 - 你的.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "神魂颠倒", artist: "邓典", src: "https://cdn-assets.bestelysia.com/金曜日/邓典 - 神魂颠倒.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "情意结", artist: "邓岳章", src: "https://cdn-assets.bestelysia.com/金曜日/邓岳章 - 情意结.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "苦咖啡·唯一", artist: "那奇沃夫/KKECHO", src: "https://cdn-assets.bestelysia.com/金曜日/那奇沃夫_KKECHO-苦咖啡·唯一.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "爱如火", artist: "那艺娜", src: "https://cdn-assets.bestelysia.com/金曜日/那艺娜-爱如火.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "你的眼睛像星星", artist: "郭正正/Old crab", src: "https://cdn-assets.bestelysia.com/金曜日/郭正正 _ Old crab - 你的眼睛像星星.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "野摩托", artist: "郭镐鸣", src: "https://cdn-assets.bestelysia.com/金曜日/郭镐鸣 - 野摩托.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "凄美地", artist: "郭顶", src: "https://cdn-assets.bestelysia.com/金曜日/郭顶-凄美地.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "自娱自乐", artist: "金志文", src: "https://cdn-assets.bestelysia.com/金曜日/金志文 - 自娱自乐.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "谁不是", artist: "金池", src: "https://cdn-assets.bestelysia.com/金曜日/金池 - 谁不是.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "恋爱画板", artist: "锦零", src: "https://cdn-assets.bestelysia.com/金曜日/锦零 - 恋爱画板.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "予你", artist: "队长", src: "https://cdn-assets.bestelysia.com/金曜日/队长 - 予你.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "哪里都是你", artist: "队长", src: "https://cdn-assets.bestelysia.com/金曜日/队长 - 哪里都是你.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "11", artist: "队长/黄礼格", src: "https://cdn-assets.bestelysia.com/金曜日/队长 _ 黄礼格 - 11.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "后来的风", artist: "陆三三", src: "https://cdn-assets.bestelysia.com/金曜日/陆三三 - 后来的风.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "人世间", artist: "雷佳", src: "https://cdn-assets.bestelysia.com/金曜日/雷佳 - 人世间.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "独到", artist: "高睿", src: "https://cdn-assets.bestelysia.com/金曜日/高睿 - 独到.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "叹", artist: "黄龄/Tăng Duy Tân", src: "https://cdn-assets.bestelysia.com/金曜日/黄龄 _ Tăng Duy Tân - 叹.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "武家坡2021", artist: "龍猛寺寬度", src: "https://cdn-assets.bestelysia.com/金曜日/龍猛寺寬度 - 武家坡2021.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "Sweet", artist: "龚俊", src: "https://cdn-assets.bestelysia.com/金曜日/龚俊 - Sweet.mp3", cover: "assets/Elysia11.jpg", category: "fri" },

  { title: "等不到的你", artist: "一只白羊", src: "https://cdn-assets.bestelysia.com/金曜日/一只白羊 - 等不到的你.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "赐我", artist: "一只白羊", src: "https://cdn-assets.bestelysia.com/金曜日/一只白羊 - 赐我.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "海市蜃楼", artist: "三叔说", src: "https://cdn-assets.bestelysia.com/金曜日/三叔说 - 海市蜃楼.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "从前怕", artist: "于冬然", src: "https://cdn-assets.bestelysia.com/金曜日/于冬然 - 从前怕.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "我的眼泪你的战利品", artist: "于冬然", src: "https://cdn-assets.bestelysia.com/金曜日/于冬然 - 我的眼泪你的战利品.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "故事还长", artist: "云汐", src: "https://cdn-assets.bestelysia.com/金曜日/云汐-故事还长.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "后来的我们", artist: "五月天", src: "https://cdn-assets.bestelysia.com/金曜日/五月天 - 后来的我们.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "玫瑰少年", artist: "五月天", src: "https://cdn-assets.bestelysia.com/金曜日/五月天 - 玫瑰少年.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "悲伤的爱情", artist: "任夏", src: "https://cdn-assets.bestelysia.com/金曜日/任夏 - 悲伤的爱情.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "那一刻心动", artist: "任子墨", src: "https://cdn-assets.bestelysia.com/金曜日/任子墨 - 那一刻心动.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "后来我们的爱 (萝卜版)", artist: "原来是萝卜丫", src: "https://cdn-assets.bestelysia.com/金曜日/原来是萝卜丫 - 后来我们的爱 (萝卜版).mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "我曾遇到一束光", artist: "叶斯淳", src: "https://cdn-assets.bestelysia.com/金曜日/叶斯淳 - 我曾遇到一束光.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "回不去的从前", artist: "周延英", src: "https://cdn-assets.bestelysia.com/金曜日/周延英子回不去的从前.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "我看过", artist: "周星星", src: "https://cdn-assets.bestelysia.com/金曜日/周星星我看过.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "毒药", artist: "周星星", src: "https://cdn-assets.bestelysia.com/金曜日/周星星毒药.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "玫瑰少年 (Live)", artist: "周深/GAI周延", src: "https://cdn-assets.bestelysia.com/金曜日/周深GAI周延玫瑰少年Live.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "若思念便思念", artist: "周深", src: "https://cdn-assets.bestelysia.com/金曜日/周深若思念便思念.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "想去海边", artist: "夏日入侵企画", src: "https://cdn-assets.bestelysia.com/金曜日/夏日入侵企画 - 想去海边.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "雾里", artist: "姚六一", src: "https://cdn-assets.bestelysia.com/金曜日/姚六一 - 雾里.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "失眠的夜 (DJ热搜版)", artist: "宋孟君", src: "https://cdn-assets.bestelysia.com/金曜日/宋孟君 - 失眠的夜 (DJ热搜版).mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "那年·年少", artist: "宋宇宁", src: "https://cdn-assets.bestelysia.com/金曜日/宋宇宁 - 那年·年少.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "就让这大雨全都落下", artist: "容祖儿", src: "https://cdn-assets.bestelysia.com/金曜日/容祖儿-就让这大雨全都落下-汪苏泷概念创作集《联名》作品.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "我走后", artist: "小咪", src: "https://cdn-assets.bestelysia.com/金曜日/小咪-我走后.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "爱都爱了", artist: "小洲", src: "https://cdn-assets.bestelysia.com/金曜日/小洲 - 爱都爱了.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "我怕来者不是你", artist: "小蓝背心", src: "https://cdn-assets.bestelysia.com/金曜日/小蓝背心 - 我怕来者不是你.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "目及皆是你", artist: "小蓝背心", src: "https://cdn-assets.bestelysia.com/金曜日/小蓝背心 - 目及皆是你.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "从前说", artist: "小阿七", src: "https://cdn-assets.bestelysia.com/金曜日/小阿七 - 从前说.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "向云端", artist: "小霞/海洋Bo", src: "https://cdn-assets.bestelysia.com/金曜日/小霞,海洋Bo - 向云端.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "落在生命里的光", artist: "尹昔眠", src: "https://cdn-assets.bestelysia.com/金曜日/尹昔眠 - 落在生命里的光.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "全体诺克萨斯国战士还是劈开", artist: "张叶蕾", src: "https://cdn-assets.bestelysia.com/金曜日/张叶蕾全体诺克萨斯国战士还是劈开.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "迟来的情话", artist: "张家旺", src: "https://cdn-assets.bestelysia.com/金曜日/张家旺 - 迟来的情话.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "如故", artist: "张碧晨", src: "https://cdn-assets.bestelysia.com/金曜日/张碧晨 - 如故.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "开往早晨的午夜", artist: "张碧晨", src: "https://cdn-assets.bestelysia.com/金曜日/张碧晨 - 开往早晨的午夜.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "笼", artist: "张碧晨", src: "https://cdn-assets.bestelysia.com/金曜日/张碧晨 - 笼.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "心形氧气", artist: "张筛子/叶匡衡", src: "https://cdn-assets.bestelysia.com/金曜日/张筛子 _ 叶匡衡 - 心形氧气.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "可不可以", artist: "张紫豪", src: "https://cdn-assets.bestelysia.com/金曜日/张紫豪可不可以.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "篇章", artist: "张韶涵/王赫野", src: "https://cdn-assets.bestelysia.com/金曜日/张韶涵王赫野篇章.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "单人券", artist: "张齐山DanieL", src: "https://cdn-assets.bestelysia.com/金曜日/张齐山DanieL - 单人券.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "一样的月光", artist: "徐佳莹", src: "https://cdn-assets.bestelysia.com/金曜日/徐佳莹-一样的月光.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "不问ciaga不问别离", artist: "指尖笑", src: "https://cdn-assets.bestelysia.com/金曜日/指尖笑不问ciaga不问别离.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "我不是刘德华", artist: "新地/卢克", src: "https://cdn-assets.bestelysia.com/金曜日/新地 _ 卢克 - 我不是刘德华.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "傻瓜", artist: "时代少年团", src: "https://cdn-assets.bestelysia.com/金曜日/时代少年团 - 傻瓜.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "小小孩", artist: "时代少年团", src: "https://cdn-assets.bestelysia.com/金曜日/时代少年团 - 小小孩.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "渐暖", artist: "时代少年团", src: "https://cdn-assets.bestelysia.com/金曜日/时代少年团 - 渐暖.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "醉", artist: "时代少年团", src: "https://cdn-assets.bestelysia.com/金曜日/时代少年团 - 醉.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "樱花树下的约定（完整版）", artist: "旺仔小乔", src: "https://cdn-assets.bestelysia.com/金曜日/旺仔小乔 - 樱花树下的约定（完整版）.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "晚风告白", artist: "星野", src: "https://cdn-assets.bestelysia.com/金曜日/星野 - 晚风告白.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "半生雪", artist: "是七叔呢", src: "https://cdn-assets.bestelysia.com/金曜日/是七叔呢 - 半生雪.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "无法坠入爱河Punk Version", artist: "未来星B3Rich", src: "https://cdn-assets.bestelysia.com/金曜日/未来星B3Rich-无法坠入爱河Punk Version.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "爱上你是一个错", artist: "杨培安", src: "https://cdn-assets.bestelysia.com/金曜日/杨培安-爱上你是一个错.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "最后的人", artist: "杨小壮", src: "https://cdn-assets.bestelysia.com/金曜日/杨小壮 - 最后的人.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "后来的你在哪", artist: "树泽", src: "https://cdn-assets.bestelysia.com/金曜日/树泽 - 后来的你在哪.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "I Love You (中文版)", artist: "汪东城", src: "https://cdn-assets.bestelysia.com/金曜日/汪东城 - I Love You (中文版).mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "一路生花", artist: "温奕心", src: "https://cdn-assets.bestelysia.com/金曜日/温奕心 - 一路生花.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "偏爱和例外", artist: "烟(许佳豪)", src: "https://cdn-assets.bestelysia.com/金曜日/烟(许佳豪) - 偏爱和例外.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "删了吧", artist: "烟(许佳豪)", src: "https://cdn-assets.bestelysia.com/金曜日/烟(许佳豪) - 删了吧.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "月老掉线", artist: "王不醒", src: "https://cdn-assets.bestelysia.com/金曜日/王不醒 - 月老掉线.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "危险派对", artist: "王以太/刘至佳", src: "https://cdn-assets.bestelysia.com/金曜日/王以太 _ 刘至佳 - 危险派对.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "墨尔本的秋天 (女版)", artist: "王优秀", src: "https://cdn-assets.bestelysia.com/金曜日/王优秀 - 墨尔本的秋天 (女版).mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "我们的歌", artist: "王力宏", src: "https://cdn-assets.bestelysia.com/金曜日/王力宏-我们的歌.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "追寻你", artist: "王天戈/川青", src: "https://cdn-assets.bestelysia.com/金曜日/王天戈 _ 川青 - 追寻你.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "循迹", artist: "王子健", src: "https://cdn-assets.bestelysia.com/金曜日/王子健 - 循迹.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "循迹", artist: "王子健", src: "https://cdn-assets.bestelysia.com/金曜日/王子健-循迹.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "怨苍天变了心 (吉他版)", artist: "王小帅", src: "https://cdn-assets.bestelysia.com/金曜日/王小帅 - 怨苍天变了心 (吉他版).mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "爱你", artist: "王心凌", src: "https://cdn-assets.bestelysia.com/金曜日/王心凌 - 爱你.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "第一次爱的人", artist: "王心凌", src: "https://cdn-assets.bestelysia.com/金曜日/王心凌 - 第一次爱的人.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "去年花开", artist: "王忻辰/苏星婕", src: "https://cdn-assets.bestelysia.com/金曜日/王忻辰 _ 苏星婕 - 去年花开.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "等风吹散人海", artist: "王忻辰/葛里", src: "https://cdn-assets.bestelysia.com/金曜日/王忻辰 _ 葛里 - 等风吹散人海.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "穷叉叉", artist: "王搏", src: "https://cdn-assets.bestelysia.com/金曜日/王搏 - 穷叉叉.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "流星也为你落下来了", artist: "王源", src: "https://cdn-assets.bestelysia.com/金曜日/王源 - 流星也为你落下来了.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "如愿", artist: "王菲", src: "https://cdn-assets.bestelysia.com/金曜日/王菲 - 如愿.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "恶作剧", artist: "王蓝茵", src: "https://cdn-assets.bestelysia.com/金曜日/王蓝茵 - 恶作剧.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "会吗", artist: "王靖雯不胖", src: "https://cdn-assets.bestelysia.com/金曜日/王靖雯不胖 - 会吗.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "说说话 (Live)", artist: "王靖雯不胖", src: "https://cdn-assets.bestelysia.com/金曜日/王靖雯不胖 - 说说话 (Live).mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "木偶戏", artist: "玥夏", src: "https://cdn-assets.bestelysia.com/金曜日/玥夏 - 木偶戏.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "在你的身边", artist: "盛哲", src: "https://cdn-assets.bestelysia.com/金曜日/盛哲 - 在你的身边.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "最美的瞬间", artist: "真瑞", src: "https://cdn-assets.bestelysia.com/金曜日/真瑞最美的瞬间.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "难却 (吉他版)", artist: "祥嘞嘞", src: "https://cdn-assets.bestelysia.com/金曜日/祥嘞嘞 - 难却 (吉他版).mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "下雨夜", artist: "苏星婕", src: "https://cdn-assets.bestelysia.com/金曜日/苏星婕 - 下雨夜.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "听悲伤的情歌", artist: "苏星婕", src: "https://cdn-assets.bestelysia.com/金曜日/苏星婕 - 听悲伤的情歌.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "等一场大雨", artist: "苏星婕", src: "https://cdn-assets.bestelysia.com/金曜日/苏星婕 - 等一场大雨.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "风吹过八千里", artist: "苏星婕", src: "https://cdn-assets.bestelysia.com/金曜日/苏星婕 - 风吹过八千里.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "凤毛麟角", artist: "薛之谦", src: "https://cdn-assets.bestelysia.com/金曜日/薛之谦 - 凤毛麟角.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "变废为宝", artist: "薛之谦", src: "https://cdn-assets.bestelysia.com/金曜日/薛之谦 - 变废为宝.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "男二号", artist: "薛之谦", src: "https://cdn-assets.bestelysia.com/金曜日/薛之谦 - 男二号.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "变废为宝", artist: "薛之谦", src: "https://cdn-assets.bestelysia.com/金曜日/薛之谦-变废为宝.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "hallo每一天", artist: "薛廷佑", src: "https://cdn-assets.bestelysia.com/金曜日/薛廷佑 - hallo每一天.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "化作烟火为你坠落", artist: "袁小葳/阿辰阎", src: "https://cdn-assets.bestelysia.com/金曜日/袁小葳 _ 阿辰阎 -化作烟火为你坠落.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "早安隆回", artist: "袁树雄", src: "https://cdn-assets.bestelysia.com/金曜日/袁树雄 - 早安隆回.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "诀爱", artist: "詹雯婷", src: "https://cdn-assets.bestelysia.com/金曜日/詹雯婷 - 诀爱.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "爱丫爱丫", artist: "许66", src: "https://cdn-assets.bestelysia.com/金曜日/许66 - 爱丫爱丫.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "曾经你说", artist: "赵乃吉", src: "https://cdn-assets.bestelysia.com/金曜日/赵乃吉曾经你说.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "桃桃心动", artist: "赵芷彤Cassie", src: "https://cdn-assets.bestelysia.com/金曜日/赵芷彤Cassie桃桃心动.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "我记得", artist: "赵雷", src: "https://cdn-assets.bestelysia.com/金曜日/赵雷我记得.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "路过人间", artist: "郁可唯", src: "https://cdn-assets.bestelysia.com/金曜日/郁可唯 - 路过人间.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "去有风的地方", artist: "郁可唯", src: "https://cdn-assets.bestelysia.com/金曜日/郁可唯-去有风的地方-《去有风的地方》电视剧主题曲.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "如果呢", artist: "郑润泽", src: "https://cdn-assets.bestelysia.com/金曜日/郑润泽如果呢.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "怎叹", artist: "郑鱼", src: "https://cdn-assets.bestelysia.com/金曜日/郑鱼怎叹.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "不舍", artist: "颜人中", src: "https://cdn-assets.bestelysia.com/金曜日/颜人中 - 不舍.mp3", cover: "assets/Elysia11.jpg", category: "fri" },
  { title: "有些", artist: "颜人中", src: "https://cdn-assets.bestelysia.com/金曜日/颜人中 - 有些.mp3", cover: "assets/Elysia11.jpg", category: "fri" },

    { title: "My Soul, Your Beats!", artist: "Lia (Piano Arr.)", src: "assets/My Soul, Your Beats! -Piano Arrange Ver.-.mp3", cover: "assets/My Soul, Your Beats! -Piano Arrange Ver.-.jpg", category: "piano" },
    { title: "My Most Precious Treasure", artist: "Angel Beats!", src: "assets/My Most Precious Treasure (From My Most Precious Treasure).mp3", cover: "assets/Key anime piano medley.jpg", category: "piano" },
    { title: "Shiteki de Souseiteki na Tori-tachi e no Shirabe", artist: "Angel Beats!", src: "assets/Shiteki de Souseiteki na Tori-tachi e no Shirabe (Yokunin no Tame no Piano Sanka).mp3", cover: "assets/Shiteki.jpg", category: "piano" },
    { title: "Last regrets foretting me", artist: "Kanon (Piano)", src: "assets/Last regrets,foretting me.mp3", cover: "assets/Last regrets, foretting me.jpg", lrc: "lyrics/lastregrets.lrc", category: "piano" },
    { title: "Megumeru Gensoukyoku", artist: "CLANNAD (Piano)", src: "assets/Megumeru Gensoukyoku.mp3", cover: "assets/Megumeru Gensoukyoku.jpg", category: "piano" },
    { title: "Call of Silence", artist: "Hiroyuki Sawano", src: "assets/Call of Silence (From Attack on Titian) Piano Cover.mp3", cover: "assets/Call of Silence.jpg", category: "piano" },
    { title: "Only my Railgun OP1 fripSide", artist: "fripSide (Piano)", src: "assets/Only my Railgun - A Certain Scientific Railgun OP1 [Piano]  fripSide.mp3", cover: "assets/Level5.jpg", category: "piano" },
    { title: "Aoi Tori - The iDOLM", artist: "The iDOLM@STER", src: "assets/[Pianeet] Aoi Tori - The iDOLM@STER OST - Piano Tutorial  Synthesia.mp3", cover: "assets/Aoi Tori - The iDOLM.jpg", category: "piano" },
    { title: "鬼滅之刃 OPLiSA - 紅蓮華", artist: "LiSA (Piano)", src: "assets/Gurenge - Demon Slayer OP [Piano].mp3", cover: "assets/Shinobu Kocho.jpg", category: "piano" },
    { title: "Flower Dance - DJ Okawari", artist: "DJ Okawari", src: "assets/Flower Dance - DJ Okawari (Piano Cover by Riyandi Kusuma).mp3", cover: "assets/Flower Dance - DJ Okawari.jpg", category: "piano" },
    { title: "theme of SSS -Piano Arrange ", artist: "Angel Beats!", src: "assets/theme of SSS -Piano Arrange Ver.-.mp3", cover: "assets/theme of SSS.jpg", category: "piano" },
    { title: "My Soul Your Beats", artist: "Angel Beats!", src: "assets/My Soul, Your Beats! ~Classic~ Instrumental.mp3", cover: "assets/My Soul, Your Beats! ~Classic~ Instrumental.jpg", category: "piano" },
    { title: "Pachelbel's Canon", artist: "Bi.Bi Piano", src: "assets/Bi.Bi PianoPachelbel's Canon 终于弹了这首 世界上最治愈的钢琴曲卡农.mp3", cover: "assets/banner1.jpg", category: "piano" },
    { title: "Heroism endures in nothingness", artist: "Hoyo-Mix", src: "assets/英雄主义-在虚无中永存.mp3", cover: "assets/Elysia11.jpg", category: "piano" },
    { title: "诀别书", artist: "Piano Cover", src: "assets/钢琴演奏诀别书纯音乐精编完整版.mp3", cover: "assets/Elysia11.jpg", category: "piano" },
    { title: "Key anime piano medley", artist: "Key Sounds Label", src: "assets/Air (TV), Kanon (2006), Clannad After Story - Key anime piano medley.mp3", cover: "assets/Key anime piano medley.jpg", category: "piano" },
    { title: "Crying for Rain", artist: "Minami (Piano)", src: "assets/Crying for Rain (Kawaki wo Ameku) - Domestic na Kanojo OP [Piano]  Minami.mp3", cover: "assets/banner1.jpg", category: "piano" },
    { title: "GIRLS BAND CRY", artist: "TOGENASHI TOGEARI", src: "assets/GIRLS BAND CRY OP - Wrong World - Piano Cover  TOGENASHI TOGEARI.mp3", cover: "assets/GIRLS BAND CRY.jpg", category: "piano" },
    { title: "Hikari no Senritsu", artist: "Animenz (Kalafina)", src: "assets/Hikari no Senritsu - Sora no Woto OP Arr. Animenz (2024 Fan Remaster Visualized).mp3", cover: "assets/banner1.jpg", category: "piano" },
    { title: "LEVEL5 -judgelight", artist: "fripSide (Piano)", src: "assets/LEVEL5 -judgelight- A Certain Scientific Railgun OP2 [Piano].mp3", cover: "assets/banner1.jpg", category: "piano" },
    { title: "Flower Dance Super Trick Version", artist: "DJ Okawari", src: "assets/Flower Dance Super Trick Version (mp3cut.net).mp3", cover: "assets/Flower Dance - DJ Okawari.jpg", category: "piano" },
    { title: "Departures - Guilty Crown ED1", artist: "EGOIST (Piano)", src: "assets/Departures - Guilty Crown ED1 [Piano].mp3", cover: "assets/Elysia11.jpg", category: "piano" },
    { title: "Majo no Tabitabi", artist: "Piano Cover", src: "assets/Majo no Tabitabi OPLiterature Piano Cover.mp3", cover: "assets/Majo no Tabitabi.jpg", category: "piano" },
    { title: "My Dearest ", artist: "Supercell (Piano)", src: "assets/My Dearest - Guilty Crown OP [10 Year Anniversary Edition] [Piano].mp3", cover: "assets/Mydearest.jpg", category: "piano" },
    { title: "Ninelie Kabaneri", artist: "Aimer w/ Chelly", src: "assets/Ninelie - Kabaneri of the Iron Fortress ED [Piano].mp3", cover: "assets/ninelie.jpg", category: "piano" },
    { title: "One Last Kiss", artist: "Hikaru Utada (Piano)", src: "assets/One Last Kiss - Evangelion_ 3.0  1.0 Theme Song [Piano]  Hikaru Utada.mp3", cover: "assets/one last kiss.jpg", category: "piano" },
    { title: "secret base", artist: "Zone (Piano)", src: "assets/secret base - Kimi ga Kureta Mono - AnoHana ED [Piano].mp3", cover: "assets/secret base.jpg", category: "piano" },
    { title: "Blue Bird 2022 ver", artist: "Ikimono-gakari", src: "assets/Blue Bird (2022 ver.) - Naruto Shippuuden OP3 [Piano]  Ikimono-gakari.mp3", cover: "assets/banner1.jpg", category: "piano" },
    { title: "Hikaru Nara - Your Lie in Apri", artist: "Goose House (Piano)", src: "assets/Hikaru Nara - Your Lie in April OP1 [Piano].mp3", cover: "assets/Elysia11.jpg", category: "piano" },
    { title: "AKIBA POP the Future - Pianeet", artist: "Pianeet", src: "assets/AKIBA POP the Future - Pianeet [Piano Transcription].mp3", cover: "assets/banner1.jpg", category: "piano" },
    { title: "SWORD ART ONLINE", artist: "Animenz", src: "assets/SWORD ART ONLINE PIANO MEDLEY!!! (30,000 Subscribers Special).mp3", cover: "assets/SWORD ART ONLINE.jpg", category: "piano" },
    { title: "Merry Christmas, Mr. Lawrence 1986", artist: "Ryuichi Sakamoto", src: "assets/merry.mp3", cover: "assets/banner1.jpg", category: "piano" },
    { title: "反方向的钟", artist: "周杰倫", src: "assets/反方向的钟.mp3", cover: "assets/Elysia11.jpg", category: "piano" },
    { title: "给我一首歌的时间", artist: "周杰倫", src: "assets/给我一首歌的时间 piano ver-.mp3", cover: "assets/banner1.jpg", category: "piano" },
    { title: "晴天", artist: "Bi.Bi Piano", src: "assets/周杰伦晴天 钢琴独奏 Jay ChouBi.Bi Piano.mp3", cover: "assets/banner1.jpg", category: "piano" },
    { title: "溯", artist: "CORSAK", src: "assets/su.mp3", cover: "assets/Elysia11.jpg", category: "piano" },
    { title: "潮汐", artist: "Imagine Dragons", src: "assets/Natural.mp3", cover: "assets/Elysia11.jpg", category: "piano" },
    { title: "游京", artist: "东雪莲", src: "assets/游京 东雪莲.mp3", cover: "assets/游京 东雪莲.jpg", category: "piano" },
    { title: "还是会想你", artist: "林达浪", src: "assets/还是会想你曼波 (mp3cut.net) 2.mp3", cover: "assets/Elysia11.jpg", category: "piano" },
    { title: "Duvert 四季 Merry mixed", artist: "Mixed", src: "assets/mix.mp3", cover: "assets/Elysia11.jpg", category: "piano" }
  ];
